#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
ONIT-PNG Security Audit Report Generator
Generates a comprehensive security audit PDF with recommendations.
"""

import os, sys, hashlib
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch, cm, mm
from reportlab.lib import colors
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_JUSTIFY, TA_RIGHT
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    PageBreak, KeepTogether, CondPageBreak, Image
)
from reportlab.platypus.tableofcontents import TableOfContents
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase.pdfmetrics import registerFontFamily

# ───────────────────────────────────────────────────────────
# Palette (auto-generated by pdf.py palette.generate)
# ───────────────────────────────────────────────────────────
ACCENT       = colors.HexColor('#4927b0')
TEXT_PRIMARY  = colors.HexColor('#1f2122')
TEXT_MUTED    = colors.HexColor('#81878d')
BG_SURFACE   = colors.HexColor('#dce0e4')
BG_PAGE      = colors.HexColor('#edeff1')

TABLE_HEADER_COLOR = ACCENT
TABLE_HEADER_TEXT  = colors.white
TABLE_ROW_EVEN     = colors.white
TABLE_ROW_ODD      = BG_SURFACE

# Semantic colors for severity
SEV_CRITICAL = colors.HexColor('#dc2626')
SEV_HIGH     = colors.HexColor('#ea580c')
SEV_MEDIUM   = colors.HexColor('#d97706')
SEV_LOW      = colors.HexColor('#65a30d')
SEV_INFO     = colors.HexColor('#0284c7')

# ───────────────────────────────────────────────────────────
# Font Registration
# ───────────────────────────────────────────────────────────
pdfmetrics.registerFont(TTFont('LiberationSerif', '/usr/share/fonts/truetype/liberation/LiberationSerif-Regular.ttf'))
pdfmetrics.registerFont(TTFont('LiberationSerif-Bold', '/usr/share/fonts/truetype/liberation/LiberationSerif-Bold.ttf'))
pdfmetrics.registerFont(TTFont('Carlito', '/usr/share/fonts/truetype/english/Carlito-Regular.ttf'))
pdfmetrics.registerFont(TTFont('Carlito-Bold', '/usr/share/fonts/truetype/english/Carlito-Bold.ttf'))
pdfmetrics.registerFont(TTFont('DejaVuSans', '/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf'))
pdfmetrics.registerFont(TTFont('DejaVuSans-Bold', '/usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf'))
pdfmetrics.registerFont(TTFont('SarasaMonoSC', '/usr/share/fonts/truetype/chinese/SarasaMonoSC-Regular.ttf'))

registerFontFamily('LiberationSerif', normal='LiberationSerif', bold='LiberationSerif-Bold')
registerFontFamily('Carlito', normal='Carlito', bold='Carlito-Bold')
registerFontFamily('DejaVuSans', normal='DejaVuSans', bold='DejaVuSans-Bold')

# Install font fallback for mixed CJK/Latin
_pdf_scripts = os.path.join(os.path.expanduser('~'), 'my-project', 'skills', 'pdf', 'scripts')
if os.path.exists(_pdf_scripts):
    sys.path.insert(0, _pdf_scripts)
    try:
        from pdf import install_font_fallback
        install_font_fallback()
    except Exception:
        pass

# ───────────────────────────────────────────────────────────
# Page dimensions
# ───────────────────────────────────────────────────────────
PAGE_W, PAGE_H = A4
LEFT_MARGIN = 1.0 * inch
RIGHT_MARGIN = 1.0 * inch
TOP_MARGIN = 0.8 * inch
BOTTOM_MARGIN = 0.8 * inch
AVAILABLE_WIDTH = PAGE_W - LEFT_MARGIN - RIGHT_MARGIN
H1_ORPHAN_THRESHOLD = (PAGE_H - TOP_MARGIN - BOTTOM_MARGIN) * 0.15

# ───────────────────────────────────────────────────────────
# Styles
# ───────────────────────────────────────────────────────────
body_font = 'LiberationSerif'
heading_font = 'LiberationSerif'
code_font = 'DejaVuSans'

styles = getSampleStyleSheet()

style_body = ParagraphStyle(
    name='AuditBody', fontName=body_font, fontSize=10.5, leading=18,
    alignment=TA_JUSTIFY, spaceAfter=8, wordWrap='CJK'
)
style_body_left = ParagraphStyle(
    name='AuditBodyLeft', fontName=body_font, fontSize=10.5, leading=18,
    alignment=TA_LEFT, spaceAfter=8
)
style_h1 = ParagraphStyle(
    name='AuditH1', fontName=heading_font, fontSize=20, leading=28,
    alignment=TA_LEFT, spaceBefore=18, spaceAfter=12,
    textColor=ACCENT
)
style_h2 = ParagraphStyle(
    name='AuditH2', fontName=heading_font, fontSize=15, leading=22,
    alignment=TA_LEFT, spaceBefore=14, spaceAfter=8,
    textColor=ACCENT
)
style_h3 = ParagraphStyle(
    name='AuditH3', fontName=heading_font, fontSize=12, leading=18,
    alignment=TA_LEFT, spaceBefore=10, spaceAfter=6,
    textColor=TEXT_PRIMARY
)
style_callout = ParagraphStyle(
    name='AuditCallout', fontName=body_font, fontSize=10.5, leading=17,
    alignment=TA_LEFT, spaceAfter=8, leftIndent=24,
    borderPadding=6, borderColor=ACCENT, borderWidth=0,
    backColor=colors.HexColor('#f3f0fa')
)
style_code = ParagraphStyle(
    name='AuditCode', fontName=code_font, fontSize=8.5, leading=13,
    alignment=TA_LEFT, spaceAfter=6, leftIndent=12,
    backColor=colors.HexColor('#f1f5f9')
)
style_toc_h1 = ParagraphStyle(
    name='TOCH1', fontName=heading_font, fontSize=13, leftIndent=20
)
style_toc_h2 = ParagraphStyle(
    name='TOCH2', fontName=heading_font, fontSize=11, leftIndent=40
)

# Table styles
style_th = ParagraphStyle(
    name='TableHeader', fontName=heading_font, fontSize=10,
    textColor=colors.white, alignment=TA_CENTER, leading=14
)
style_td = ParagraphStyle(
    name='TableCell', fontName=body_font, fontSize=9.5,
    textColor=TEXT_PRIMARY, alignment=TA_LEFT, leading=14, wordWrap='CJK'
)
style_td_center = ParagraphStyle(
    name='TableCellCenter', fontName=body_font, fontSize=9.5,
    textColor=TEXT_PRIMARY, alignment=TA_CENTER, leading=14
)

# ───────────────────────────────────────────────────────────
# TOC-enabled DocTemplate
# ───────────────────────────────────────────────────────────
class TocDocTemplate(SimpleDocTemplate):
    def afterFlowable(self, flowable):
        if hasattr(flowable, 'bookmark_name'):
            level = getattr(flowable, 'bookmark_level', 0)
            text = getattr(flowable, 'bookmark_text', '')
            key = getattr(flowable, 'bookmark_key', '')
            self.notify('TOCEntry', (level, text, self.page, key))

def add_heading(text, style, level=0):
    key = 'h_%s' % hashlib.md5(text.encode()).hexdigest()[:8]
    p = Paragraph('<a name="%s"/>%s' % (key, text), style)
    p.bookmark_name = text
    p.bookmark_level = level
    p.bookmark_text = text
    p.bookmark_key = key
    return p

def add_major_section(text, style):
    return [
        CondPageBreak(H1_ORPHAN_THRESHOLD),
        add_heading(text, style, level=0),
    ]

def safe_keep_together(elements):
    total_h = 0
    for el in elements:
        try:
            w, h = el.wrap(AVAILABLE_WIDTH, PAGE_H)
            total_h += h
        except:
            total_h += 50
    if total_h <= PAGE_H * 0.4:
        return [KeepTogether(elements)]
    elif len(elements) >= 2:
        return [KeepTogether(elements[:2])] + list(elements[2:])
    return list(elements)

# ───────────────────────────────────────────────────────────
# Helper: severity badge
# ───────────────────────────────────────────────────────────
def sev_badge(text, color):
    return Paragraph(
        '<font color="%s"><b>%s</b></font>' % (color.hexval(), text),
        style_td_center
    )

def sev_style(severity):
    m = {
        'CRITIQUE': (SEV_CRITICAL, 'CRITIQUE'),
        'ELEVEE': (SEV_HIGH, 'ELEVEE'),
        'MOYENNE': (SEV_MEDIUM, 'MOYENNE'),
        'FAIBLE': (SEV_LOW, 'FAIBLE'),
        'INFO': (SEV_INFO, 'INFO'),
    }
    c, t = m.get(severity, (TEXT_MUTED, severity))
    return sev_badge(t, c)

# ───────────────────────────────────────────────────────────
# Page number callback
# ───────────────────────────────────────────────────────────
def add_page_number(canvas, doc):
    page_num = canvas.getPageNumber()
    text = "ONIT-PNG Audit de Securite  |  Page %d" % page_num
    canvas.saveState()
    canvas.setFont('LiberationSerif', 8)
    canvas.setFillColor(TEXT_MUTED)
    canvas.drawString(LEFT_MARGIN, 0.4 * inch, text)
    canvas.restoreState()

# ───────────────────────────────────────────────────────────
# Build the document
# ───────────────────────────────────────────────────────────
output_path = '/home/z/my-project/download/ONIT-PNG_Audit_Securite_Rapport.pdf'
body_path = '/home/z/my-project/download/_audit_body.pdf'

doc = TocDocTemplate(
    body_path, pagesize=A4,
    leftMargin=LEFT_MARGIN, rightMargin=RIGHT_MARGIN,
    topMargin=TOP_MARGIN, bottomMargin=BOTTOM_MARGIN,
)

story = []

# ─── Table of Contents ───
story.append(Paragraph('<b>Table des matieres</b>', style_h1))
story.append(Spacer(1, 12))
toc = TableOfContents()
toc.levelStyles = [style_toc_h1, style_toc_h2]
story.append(toc)
story.append(PageBreak())

# ═══════════════════════════════════════════════════════════
# SECTION 1: Resume executif
# ═══════════════════════════════════════════════════════════
story.extend(add_major_section('1. Resume executif', style_h1))

story.append(Paragraph(
    "Ce rapport presente les resultats de l'audit de securite complet de la plateforme ONIT-PNG "
    "(Observatoire National Intelligent des Telecommunications), developpee pour l'ARPT "
    "(Autorite de Regulation des Postes et Telecommunications) de la Republique de Guinee. "
    "L'audit a ete realise sur l'ensemble de la base de code, couvrant les routes API, le systeme "
    "d'authentification, le controle d'acces base sur les roles (RBAC), la configuration de l'infrastructure, "
    "et les composants frontend.",
    style_body
))
story.append(Paragraph(
    "La plateforme ONIT-PNG est une application Next.js 16 utilisant Prisma ORM avec SQLite, "
    "NextAuth v4 pour l'authentification, et un systeme RBAC personnalise avec des politiques "
    "de controle d'acces aux donnees (Data Access Policies). L'application gere des donnees sensibles "
    "de telecommunications incluant des mesures de qualite de service (QoS), des scores d'operateurs, "
    "des alertes de zones blanches, et des rapports reglementaires. La nature de ces donnees, "
    "qui touche a la regulation nationale et aux informations commerciales des operateurs, "
    "impose des exigences de securite elevees.",
    style_body
))
story.append(Paragraph(
    "L'audit a identifie <b>27 vulnerabilites et points d'amelioration</b>, dont 3 de severite critique, "
    "5 de severite elevee, 9 de severite moyenne, et 10 de severite faible ou informationnelle. "
    "Les problemes les plus preoccupants concernent la gestion des secrets cryptographiques, "
    "les faiblesses du systeme de controle d'acces RBAC, l'utilisation de SQLite en production, "
    "et l'absence de certaines protections de securite essentielles comme les en-tetes CSP "
    "et la limitation du debit sur les endpoints critiques.",
    style_body
))

# Summary table
summary_data = [
    [Paragraph('<b>Severite</b>', style_th), Paragraph('<b>Nombre</b>', style_th), Paragraph('<b>Exemples cles</b>', style_th)],
    [sev_badge('CRITIQUE', SEV_CRITICAL), Paragraph('3', style_td_center),
     Paragraph('Secret JWT previsibles, mot de passe partage, credentials exposes cote client', style_td)],
    [sev_badge('ELEVEE', SEV_HIGH), Paragraph('5', style_td_center),
     Paragraph('RLS inefficace pour PUBLIC, scores accessibles sans auth, pas de rate limiting auth', style_td)],
    [sev_badge('MOYENNE', SEV_MEDIUM), Paragraph('9', style_td_center),
     Paragraph('SQLite en production, absence CSP, CORS non configure, signalement public sans protection', style_td)],
    [sev_badge('FAIBLE/INFO', SEV_LOW), Paragraph('10', style_td_center),
     Paragraph('Pas de rotation de session, logging insuffisant, absence d\'endpoint sante', style_td)],
]
cw = [AVAILABLE_WIDTH * 0.20, AVAILABLE_WIDTH * 0.12, AVAILABLE_WIDTH * 0.68]
t = Table(summary_data, colWidths=cw, hAlign='CENTER')
t.setStyle(TableStyle([
    ('BACKGROUND', (0, 0), (-1, 0), TABLE_HEADER_COLOR),
    ('TEXTCOLOR', (0, 0), (-1, 0), TABLE_HEADER_TEXT),
    ('BACKGROUND', (0, 1), (-1, 1), TABLE_ROW_EVEN),
    ('BACKGROUND', (0, 2), (-1, 2), TABLE_ROW_ODD),
    ('BACKGROUND', (0, 3), (-1, 3), TABLE_ROW_EVEN),
    ('BACKGROUND', (0, 4), (-1, 4), TABLE_ROW_ODD),
    ('GRID', (0, 0), (-1, -1), 0.5, TEXT_MUTED),
    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ('LEFTPADDING', (0, 0), (-1, -1), 8),
    ('RIGHTPADDING', (0, 0), (-1, -1), 8),
    ('TOPPADDING', (0, 0), (-1, -1), 6),
    ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
]))
story.append(Spacer(1, 18))
story.append(t)
story.append(Spacer(1, 6))
story.append(Paragraph('Tableau 1 : Synthese des vulnerabilites identifiees par severite', ParagraphStyle(
    name='Caption', fontName=body_font, fontSize=9, alignment=TA_CENTER, textColor=TEXT_MUTED
)))
story.append(Spacer(1, 18))

# ═══════════════════════════════════════════════════════════
# SECTION 2: Presentation de la plateforme
# ═══════════════════════════════════════════════════════════
story.extend(add_major_section('2. Presentation de la plateforme ONIT-PNG', style_h1))

story.append(add_heading('2.1 Architecture technique', style_h2))
story.append(Paragraph(
    "La plateforme ONIT-PNG est construite sur une architecture monolithique Next.js 16 avec "
    "rendu cote serveur (SSR) et routes API integrees. Le framework utilise React 19 pour le "
    "frontend, avec une interface sombre (dark mode) et un systeme de navigation par onglets "
    "adaptatif selon le role de l'utilisateur. L'application est depoyee via Docker avec un "
    "build multi-stage et une base de donnees SQLite embarquee, ce qui simplifie le deploiement "
    "mais pose des questions de scalabilite et de securite en production.",
    style_body
))

tech_data = [
    [Paragraph('<b>Composant</b>', style_th), Paragraph('<b>Technologie</b>', style_th), Paragraph('<b>Version</b>', style_th)],
    [Paragraph('Framework', style_td), Paragraph('Next.js', style_td), Paragraph('16.1.1', style_td_center)],
    [Paragraph('Frontend', style_td), Paragraph('React + Recharts + Leaflet', style_td), Paragraph('19.0', style_td_center)],
    [Paragraph('ORM', style_td), Paragraph('Prisma', style_td), Paragraph('6.11.1', style_td_center)],
    [Paragraph('Base de donnees', style_td), Paragraph('SQLite', style_td), Paragraph('Embarquee', style_td_center)],
    [Paragraph('Authentification', style_td), Paragraph('NextAuth v4 (Credentials)', style_td), Paragraph('4.x', style_td_center)],
    [Paragraph('Validation', style_td), Paragraph('Zod', style_td), Paragraph('4.4.3', style_td_center)],
    [Paragraph('Hash mots de passe', style_td), Paragraph('bcryptjs', style_td), Paragraph('3.0.3', style_td_center)],
    [Paragraph('Conteneurisation', style_td), Paragraph('Docker (multi-stage)', style_td), Paragraph('Node 20 Alpine', style_td_center)],
]
cw2 = [AVAILABLE_WIDTH * 0.30, AVAILABLE_WIDTH * 0.45, AVAILABLE_WIDTH * 0.25]
t2 = Table(tech_data, colWidths=cw2, hAlign='CENTER')
row_styles = []
for i in range(1, len(tech_data)):
    bg = TABLE_ROW_EVEN if i % 2 == 1 else TABLE_ROW_ODD
    row_styles.append(('BACKGROUND', (0, i), (-1, i), bg))
t2.setStyle(TableStyle([
    ('BACKGROUND', (0, 0), (-1, 0), TABLE_HEADER_COLOR),
    ('TEXTCOLOR', (0, 0), (-1, 0), TABLE_HEADER_TEXT),
    ('GRID', (0, 0), (-1, -1), 0.5, TEXT_MUTED),
    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ('LEFTPADDING', (0, 0), (-1, -1), 8),
    ('RIGHTPADDING', (0, 0), (-1, -1), 8),
    ('TOPPADDING', (0, 0), (-1, -1), 5),
    ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
] + row_styles))
story.append(Spacer(1, 12))
story.append(t2)
story.append(Spacer(1, 6))
story.append(Paragraph('Tableau 2 : Stack technique de la plateforme', ParagraphStyle(
    name='Caption2', fontName=body_font, fontSize=9, alignment=TA_CENTER, textColor=TEXT_MUTED
)))

story.append(add_heading('2.2 Modele de donnees et roles', style_h2))
story.append(Paragraph(
    "Le schema Prisma definit 9 roles distincts allant de SUPER_ADMIN a PUBLIC, avec un systeme "
    "de permissions granulaires base sur des tuples (ressource, action). Les politiques de controle "
    "d'acces aux donnees (DataAccessPolicy) implementent un filtrage de type Row-Level Security (RLS) "
    "avec des scopes : all, public_only, own_region, own_org. Le modele comprend 13 entites principales "
    "couvrant les utilisateurs, les roles, les operateurs telecoms, les regions, les campagnes de mesures, "
    "les mesures QoS, les scores d'operateurs, les alertes, les rapports, et les journaux d'audit. "
    "Chaque role possede des permissions specifiques qui determinent l'acces aux differentes fonctionnalites "
    "et aux donnees selon le principe du moindre privilege.",
    style_body
))

# ═══════════════════════════════════════════════════════════
# SECTION 3: Vulnerabilites critiques
# ═══════════════════════════════════════════════════════════
story.extend(add_major_section('3. Vulnerabilites critiques', style_h1))

# VULN-01
story.append(add_heading('3.1 VULN-01 : Secret JWT previsible (NEXTAUTH_SECRET)', style_h2))
story.append(Paragraph(
    '<b>Severite :</b> CRITIQUE | <b>Fichier :</b> .env | <b>CWE :</b> CWE-321 (Use of Hard-coded Cryptographic Key)',
    style_callout
))
story.append(Paragraph(
    "Le fichier .env contient un secret JWT previsible : "
    "<font name='DejaVuSans'>onit-png-secret-key-CHANGE-ME-IN-PRODUCTION</font>. "
    "Ce secret est utilise pour signer et verifier tous les tokens JWT de session. Un attaquant "
    "connaissant cette valeur peut forger des tokens d'authentification valides pour n'importe quel "
    "utilisateur, y compris SUPER_ADMIN, et obtenir un acces complet a la plateforme. Ce type "
    "d'attaque est particulierement dangereux car il ne laisse aucune trace dans les journaux d'audit, "
    "le token etant cryptographiquement valide.",
    style_body
))
story.append(Paragraph(
    "Bien que le fichier docker-compose.yml exige que NEXTAUTH_SECRET soit defini via "
    "<font name='DejaVuSans'>${NEXTAUTH_SECRET:?}</font>, le fichier .env actif contient toujours "
    "la valeur par defaut. De plus, le fichier .env.example contient la valeur "
    "<font name='DejaVuSans'>changez-cette-valeur-en-production</font>, ce qui suggere que "
    "cette valeur n'a jamais ete changee dans les environnements de deploiement.",
    style_body
))
story.append(Paragraph('<b>Recommandation :</b>', style_h3))
story.append(Paragraph(
    "Generer un secret aleatoire fort pour chaque environnement avec "
    "<font name='DejaVuSans'>openssl rand -base64 32</font> et le stocker dans un gestionnaire "
    "de secrets (HashiCorp Vault, AWS Secrets Manager, ou variables d'environnement securisees). "
    "Ne jamais committer de secrets dans le depot de code. Ajouter .env au fichier .gitignore "
    "et implementer une verification au demarrage qui refuse de lancer l'application si le secret "
    "correspond a une valeur par defaut connue.",
    style_body
))

# VULN-02
story.append(add_heading('3.2 VULN-02 : Mot de passe partage pour tous les utilisateurs seed', style_h2))
story.append(Paragraph(
    '<b>Severite :</b> CRITIQUE | <b>Fichier :</b> prisma/seed.ts | <b>CWE :</b> CWE-259 (Use of Hard-coded Password)',
    style_callout
))
story.append(Paragraph(
    "Le script de seeding (prisma/seed.ts) cree 10 utilisateurs avec le meme mot de passe "
    "<font name='DejaVuSans'>Admin@2026!</font>, qui est en outre imprime dans la console "
    "lors de l'execution. Parmi ces utilisateurs, on trouve des comptes critiques comme "
    "<font name='DejaVuSans'>admin@arpt.gn</font> (SUPER_ADMIN), "
    "<font name='DejaVuSans'>dg@arpt.gn</font> (Directeur General), et des comptes operateurs "
    "comme <font name='DejaVuSans'>tech@orange.gn</font>. Si l'un de ces comptes est compromis, "
    "l'attaquant a acces a tous les autres comptes, creant un effet domino particulierement dangereux "
    "pour les comptes a privileges eleves.",
    style_body
))
story.append(Paragraph(
    "De plus, le fait que le mot de passe soit affiche en clair dans les logs du seed cree un risque "
    "supplementaire d'exposition dans les systemes de logging centralises, les artefacts CI/CD, "
    "et les captures d'ecran de debogage. Ce motif est contraire aux bonnes pratiques de securite "
    "qui exigent des mots de passe uniques et generes aleatoirement pour chaque compte.",
    style_body
))
story.append(Paragraph('<b>Recommandation :</b>', style_h3))
story.append(Paragraph(
    "Generer des mots de passe uniques et aleatoires pour chaque utilisateur lors du seed, "
    "et les stocker de maniere securisee (vault, fichier chiffre). Ne jamais afficher les mots "
    "de passe dans les logs. Pour les environnements de demonstration, utiliser des identifiants "
    "clairement marques comme non-productifs avec des mots de passe temporaires qui expirent. "
    "Implementer une politique de rotation des mots de passe obligeant les utilisateurs a changer "
    "leur mot de passe a la premiere connexion.",
    style_body
))

# VULN-03
story.append(add_heading('3.3 VULN-03 : Identifiants exposes dans le code client', style_h2))
story.append(Paragraph(
    '<b>Severite :</b> CRITIQUE | <b>Fichier :</b> src/components/login-modal.tsx | <b>CWE :</b> CWE-200 (Exposure of Sensitive Information)',
    style_callout
))
story.append(Paragraph(
    "Le composant login-modal.tsx contient en dur la liste des 10 adresses email des comptes "
    "de demonstration avec leurs roles associes, cote client (navigateur). N'importe quel "
    "utilisateur consultant le code source de la page peut voir ces emails internes, ce qui "
    "revele la structure organisationnelle de l'ARPT et les roles de chaque utilisateur. "
    "Combine avec VULN-02 (mot de passe partage), cela permet a un attaquant de se connecter "
    "avec n'importe quel compte sans effort de devinement.",
    style_body
))
story.append(Paragraph(
    "L'exposition des emails internes facilite egalement les attaques d'ingenierie sociale "
    "ciblees (spear phishing), car l'attaquant connait les adresses email et les fonctions "
    "de chaque personnel. Dans un contexte regulatorire ou les operateurs telecoms sont "
    "egalement surveilles par la plateforme, cette fuite d'information est particulierement "
    "problematique.",
    style_body
))
story.append(Paragraph('<b>Recommandation :</b>', style_h3))
story.append(Paragraph(
    "Supprimer la liste de comptes de demonstration du code client. Si une fonctionnalite "
    "de connexion rapide est necessaire pour les demonstrations, l'implementer via un endpoint "
    "API securise qui ne retourne que les comptes autorises en environnement de developpement, "
    "sans exposer les adresses email reelles. En production, cette fonctionnalite doit etre "
    "completement desactivee.",
    style_body
))

# ═══════════════════════════════════════════════════════════
# SECTION 4: Vulnerabilites elevees
# ═══════════════════════════════════════════════════════════
story.extend(add_major_section('4. Vulnerabilites elevees', style_h1))

# VULN-04
story.append(add_heading('4.1 VULN-04 : Controle d\'acces RLS inefficace pour le scope public_only', style_h2))
story.append(Paragraph(
    '<b>Severite :</b> ELEVEE | <b>Fichier :</b> src/lib/rbac.ts | <b>CWE :</b> CWE-863 (Incorrect Authorization)',
    style_callout
))
story.append(Paragraph(
    "Les fonctions <font name='DejaVuSans'>getAccessibleRegions()</font> et "
    "<font name='DejaVuSans'>getAccessibleOperators()</font> dans rbac.ts retournent "
    "la liste complete de toutes les regions et operateurs lorsque le scope est "
    "<font name='DejaVuSans'>public_only</font>. Cela signifie qu'un utilisateur non authentifie "
    "avec le role PUBLIC peut acceder aux memes donnees filtrees qu'un utilisateur authentifie, "
    "contournant completement la politique de restriction d'acces. Le scope public_only devrait "
    "ne retourner que les donnees explicitement marquees comme publiques (isPublic=true), et non "
    "l'ensemble des identifiants de regions et operateurs.",
    style_body
))
story.append(Paragraph(
    "Cette vulnerabilite a un impact direct sur la confidentialite des donnees operateurs, "
    "car les endpoints /api/dashboard, /api/scoring, /api/scores et /api/map retournent "
    "des donnees detaillees (scores, mesures QoS, zones blanches) a tout utilisateur anonyme.",
    style_body
))
story.append(Paragraph('<b>Recommandation :</b>', style_h3))
story.append(Paragraph(
    "Modifier le comportement du scope public_only pour ne retourner que les donnees explicitement "
    "marquees comme publiques. Implementer un filtrage au niveau des requetes Prisma en ajoutant "
    "des conditions <font name='DejaVuSans'>where: { isPublic: true }</font> pour les rapports, "
    "et des agregations anonymisees pour les scores et mesures. Les regions et operateurs ne doivent "
    "etre accessibles que par leurs codes/noms, jamais par leurs identifiants internes.",
    style_body
))

# VULN-05
story.append(add_heading('4.2 VULN-05 : Endpoints de scores et dashboard accessibles sans authentification', style_h2))
story.append(Paragraph(
    '<b>Severite :</b> ELEVEE | <b>Fichiers :</b> src/app/api/scores/route.ts, src/app/api/dashboard/route.ts | <b>CWE :</b> CWE-306 (Missing Authentication)',
    style_callout
))
story.append(Paragraph(
    "Les endpoints /api/scores et /api/dashboard acceptent des requetes sans authentification. "
    "Lorsqu'aucune session n'est trouvee, le role est defini par defaut a PUBLIC, mais le code "
    "continue a executer les requetes de base de donnees avec le scope public_only qui, comme "
    "decrit dans VULN-04, retourne toutes les donnees. Un attaquant anonyme peut donc extraire "
    "l'integralite des scores d'operateurs, des KPIs nationaux, et des statistiques regionales, "
    "ce qui constitue une fuite massive de donnees sensibles dans un contexte regulatorire.",
    style_body
))
story.append(Paragraph('<b>Recommandation :</b>', style_h3))
story.append(Paragraph(
    "Exiger l'authentification pour tous les endpoints sauf ceux explicitement conqus pour "
    "l'acces public. Pour les donnees destinees au public, creer des endpoints dedies qui "
    "ne retournent que des agregations et des donnees anonymisees, sans identifiants internes "
    "ni detail operateur. Ajouter une verification de session dans le middleware pour les "
    "routes API sensibles.",
    style_body
))

# VULN-06
story.append(add_heading('4.3 VULN-06 : Absence de rate limiting sur l\'authentification', style_h2))
story.append(Paragraph(
    '<b>Severite :</b> ELEVEE | <b>Fichier :</b> src/middleware.ts | <b>CWE :</b> CWE-307 (Improper Restriction of Excessive Authentication Attempts)',
    style_callout
))
story.append(Paragraph(
    "Bien que le middleware implemente un rate limiting pour les tentatives de connexion "
    "(5 tentatives / 15 minutes par IP), ce mecanisme utilise un stockage en memoire "
    "(Map JavaScript) qui est perdu a chaque redemarrage du serveur et ne fonctionne pas "
    "avec plusieurs instances de l'application. En deploiement Docker avec replication ou "
    "derriere un load balancer, un attaquant peut contourner cette protection simplement en "
    "repartissant ses tentatives sur differentes instances ou en utilisant differentes adresses IP "
    "(attaque distribuee).",
    style_body
))
story.append(Paragraph(
    "De plus, le rate limiting ne s'applique qu'au endpoint "
    "<font name='DejaVuSans'>/api/auth/callback/credentials</font>, laissant les autres endpoints "
    "d'authentification comme /api/auth/register et /api/auth/forgot-password sans protection "
    "contre les abus.",
    style_body
))
story.append(Paragraph('<b>Recommandation :</b>', style_h3))
story.append(Paragraph(
    "Implementer un rate limiting persistant utilisant Redis ou la base de donnees comme "
    "backing store. Configurer egalement un rate limiting au niveau du reverse proxy (Nginx) "
    "ou du load balancer pour une protection independante du nombre d'instances. Etendre le "
    "rate limiting a tous les endpoints d'authentification et considerer l'implementation "
    "d'un mecanisme de verrouillage de compte apres un nombre defini d'echecs.",
    style_body
))

# VULN-07
story.append(add_heading('4.4 VULN-07 : Requete Prisma avec contains vulnerable a l\'injection', style_h2))
story.append(Paragraph(
    '<b>Severite :</b> ELEVEE | <b>Fichier :</b> src/lib/rbac.ts | <b>CWE :</b> CWE-89 (SQL Injection)',
    style_callout
))
story.append(Paragraph(
    "Dans la fonction <font name='DejaVuSans'>getAccessibleOperators()</font>, la ligne "
    "<font name='DejaVuSans'>where: { nom: { contains: organization.split(' ')[0] } }</font> "
    "passe une valeur derivee de l'input utilisateur directement a un filtre Prisma contains. "
    "Bien que Prisma utilise des requetes parametrees qui previennent l'injection SQL classique, "
    "l'utilisation de contains avec des metacaracteres SQLite (%, _) peut permettre des abus "
    "de type LIKE injection. Un attaquant pourrait manipuler le champ organization de son "
    "profil pour matcher des operateurs auxquels il ne devrait pas avoir acces.",
    style_body
))
story.append(Paragraph('<b>Recommandation :</b>', style_h3))
story.append(Paragraph(
    "Remplacer le filtrage par contains par une correspondance exacte ou utiliser une table "
    "de mapping explicite entre organisations et operateurs. Si le contains est necessaire, "
    "echapper les metacaracteres SQLite dans l'input avant de le passer a Prisma.",
    style_body
))

# VULN-08
story.append(add_heading('4.5 VULN-08 : Signalement public sans protection anti-abus', style_h2))
story.append(Paragraph(
    '<b>Severite :</b> ELEVEE | <b>Fichier :</b> src/app/api/alerts/route.ts | <b>CWE :</b> CWE-799 (Improper Control of Interaction Frequency)',
    style_callout
))
story.append(Paragraph(
    "L'endpoint POST /api/alerts permet la creation d'alertes de type SIGNALEMENT_PUBLIC "
    "sans authentification. Bien que cette fonctionnalite soit intentionnelle (permettre aux "
    "citoyens de signaler des problemes de couverture), l'absence de toute protection anti-abus "
    "(rate limiting, CAPTCHA, validation d'email) permet a un attaquant de spammer le systeme "
    "avec des faux signalements, inondant les equipes de supervision et potentiellement masquant "
    "de vraies alertes critiques.",
    style_body
))
story.append(Paragraph('<b>Recommandation :</b>', style_h3))
story.append(Paragraph(
    "Implementer un rate limiting strict sur les signalements publics (par exemple 3 signalements "
    "par heure par adresse IP), ajouter un CAPTCHA pour les soumissions non authentifiees, "
    "et considerer l'implementation d'un systeme de verification par email ou SMS pour "
    "valider les signalements. Mettre en place un systeme de deduplication pour eviter les "
    "signalements multiples du meme probleme.",
    style_body
))

# ═══════════════════════════════════════════════════════════
# SECTION 5: Vulnerabilites moyennes
# ═══════════════════════════════════════════════════════════
story.extend(add_major_section('5. Vulnerabilites moyennes', style_h1))

mid_vulns = [
    ('5.1', 'VULN-09', 'SQLite en production',
     "La base de donnees SQLite est embarquee dans le conteneur Docker avec un fichier local "
     "(file:/app/db/onit-png.db). SQLite ne supporte pas le acces concurrents en ecriture, "
     "les connexions reseau, le chiffrement au repos, ou les sauvegardes a chaud. En cas de "
     "panne du conteneur, les donnees peuvent etre corrompues si une ecriture etait en cours. "
     "Pour une plateforme regulatorire nationale manipulant des donnees sensibles de telecommunications, "
     "PostgreSQL ou MySQL sont indispensables.",
     "Migrer vers PostgreSQL avec connexion chiffree (SSL/TLS), chiffrement au repos, et "
     "sauvegardes automatiques. Configurer Prisma avec le provider postgresql et utiliser "
     "un service managed de base de donnees en production."),
    ('5.2', 'VULN-10', 'Absence d\'en-tete Content-Security-Policy',
     "Le middleware ne configure pas d\'en-tete Content-Security-Policy (CSP), laissant la "
     "page vulnerable aux attaques XSS et aux injections de scripts malveillants. Sans CSP, "
     "n\'importe quel script inline ou externe peut s\'executer dans le contexte de la page, "
     "permettant le vol de sessions et de donnees sensibles.",
     "Ajouter un en-tete CSP restrictif dans le middleware qui limite les sources de scripts, "
     "styles, et connexions aux domaines approuves. Utiliser une politique nonce-based pour "
     "les scripts inline necessaires."),
    ('5.3', 'VULN-11', 'CORS non configure',
     "Aucune configuration CORS n\'est presente sur les routes API. Par defaut, les navigateurs "
     "appliquent la same-origin policy, mais l\'absence de configuration explicite peut permettre "
     "des requetes cross-origin non autorisees dans certains scenarios. Si l\'application est "
     "hebergee derriere un proxy ou un CDN, des headers CORS permissifs par defaut pourraient "
     "exposer les API a des tiers.",
     "Configurer explicitement les headers CORS pour n\'autoriser que les origines approuvees. "
     "Restreindre les methodes HTTP autorisees et les headers de requete."),
    ('5.4', 'VULN-12', 'Absence de validation du mot de passe actuel lors du changement',
     "L\'endpoint PUT /api/users/[id] permet de modifier le mot de passe d\'un utilisateur sans "
     "exiger la validation du mot de passe actuel. Bien que l\'acces soit limite aux admins ou "
     "a l\'utilisateur lui-meme, un attaquant ayant acces a une session compromise peut changer "
     "le mot de passe sans connaitre l\'ancien, verrouillant le proprietaire legitime hors de "
     "son compte.",
     "Exiger la validation du mot de passe actuel pour tout changement de mot de passe par "
     "l\'utilisateur lui-meme. Pour les admins, implementer une verification supplementaire "
     "(2FA, confirmation par email)."),
    ('5.5', 'VULN-13', 'Pas de politique de complexite des mots de passe',
     "Le schema de validation des mots de passe (validators.ts) exige uniquement un minimum de "
     "8 caracteres, sans exigences de complexite (majuscules, minuscules, chiffres, caracteres "
     "speciaux). Cela permet des mots de passe faibles comme \'password1\' qui sont vulnerables "
     "aux attaques par dictionnaire et par force brute.",
     "Renforcer le schema Zod avec des exigences de complexite : au moins une majuscule, une "
     "minuscule, un chiffre et un caractere special. Verifier les mots de passe contre les "
     "listes de mots de passe compromis (Have I Been Pwned API) et imposer une longueur "
     "minimale de 12 caracteres pour les comptes a privileges."),
    ('5.6', 'VULN-14', 'Absence de protection CSRF sur les mutations',
     "Les routes API POST/PUT/PATCH/DELETE n\'ont pas de protection CSRF explicite au-dela "
     "du token CSRF de NextAuth. Les cookies SameSite=Lax offrent une protection partielle "
     "mais pas complete, particulierement pour les sous-domaines et les attaques via des "
     "methodes HTTP inhabituelles.",
     "Implementer des tokens anti-CSRF pour toutes les mutations, ou utiliser le mecanisme "
     "CSRF de NextAuth de maniere coherente. Considerer l\'utilisation de cookies SameSite=Strict "
     "pour les endpoints sensibles."),
    ('5.7', 'VULN-15', 'Donnees de test dans le code client (mock-data.ts)',
     "Le fichier src/lib/mock-data.ts existe dans la base de code, suggérant la presence de "
     "donnees de test dans le build de production. Si ces donnees sont incluses dans le bundle "
     "client, elles peuvent reveler la structure des donnees et des informations internes.",
     "Exclure les fichiers de donnees de test du build de production via des imports conditionnels "
     "ou des variables d\'environnement. Verifier que le bundle final ne contient aucune donnee "
     "de test."),
    ('5.8', 'VULN-16', 'Logs d\'erreur trop verbeux en production',
     "Plusieurs routes API utilisent <font name='DejaVuSans'>console.error()</font> avec l\'objet "
     "erreur complet, ce qui peut exposer des informations sensibles (stack traces, requetes SQL, "
     "variables d\'environnement) dans les logs de production. Le logger.ts enregistre egalement "
     "des metadonnees potentiellement sensibles dans les logs.",
     "Implementer un logging structure qui masque les informations sensibles en production. "
     "Ne logger que le type d\'erreur et un identifiant de trace, sans stack trace ni details "
     "internes. Utiliser un niveau de log WARN pour les erreurs utilisateur et ERROR uniquement "
     "pour les erreurs systeme."),
    ('5.9', 'VULN-17', 'Reset de mot de passe sans invalidation de session',
     "Le endpoint /api/auth/reset-password ne supprime pas les sessions existantes apres un "
     "changement de mot de passe. Un attaquant ayant compromis un compte peut continuer a "
     "acceder au compte meme apres que le proprietaire legitime a change son mot de passe.",
     "Invalider toutes les sessions existantes lors d\'un changement de mot de passe. "
     "Implementer un mecanisme de revocation de session cote serveur en utilisant la table "
     "Session du schema Prisma."),
]

for num, vid, title, desc, rec in mid_vulns:
    story.append(add_heading('%s %s : %s' % (num, vid, title), style_h2))
    story.append(Paragraph(
        '<b>Severite :</b> MOYENNE | <b>CWE :</b> Voir detail', style_callout
    ))
    story.append(Paragraph(desc, style_body))
    story.append(Paragraph('<b>Recommandation :</b>', style_h3))
    story.append(Paragraph(rec, style_body))

# ═══════════════════════════════════════════════════════════
# SECTION 6: Vulnerabilites faibles et informations
# ═══════════════════════════════════════════════════════════
story.extend(add_major_section('6. Vulnerabilites faibles et points d\'attention', style_h1))

low_vulns = [
    ('6.1', 'VULN-18', 'Absence de rotation des sessions JWT',
     "Les sessions JWT (stratege JWT, maxAge 8h) ne peuvent pas etre revoquees cote serveur. "
     "Un utilisateur dont le token est vole peut l\'utiliser pendant toute la duree de validite "
     "malgre une deconnexion ou un changement de mot de passe.",
     "Implementer un mecanisme de liste noire de tokens ou un systeme de version de session "
     "dans la base de donnees pour permettre la revocation immediate."),
    ('6.2', 'VULN-19', 'Absence d\'endpoint de sante dedie',
     "Il n\'existe pas d\'endpoint /api/health dedie. Le healthcheck Docker utilise "
     "/api/auth/session qui ne verifie pas l\'etat de la base de donnees ou des services "
     "externes. Un probleme de base de donnees ne sera pas detecte par le healthcheck.",
     "Creer un endpoint /api/health qui verifie la connexion base de donnees, l\'etat "
     "de la session, et les eventuels services externes."),
    ('6.3', 'VULN-20', 'Pas d\'expiration des alertes et de nettoyage automatique',
     "Les alertes n\'ont pas de date d\'expiration et le systeme ne nettoie pas automatiquement "
     "les vieilles alertes resolues. Avec le temps, la base de donnees SQLite va grossir "
     "indefiniment, degradant les performances.",
     "Implementer un nettoyage automatique des alertes resolues de plus de X jours et des "
     "journaux d\'audit anciens. Ajouter un index sur les champs de date pour les requetes "
     "frequentes."),
    ('6.4', 'VULN-21', 'Absence d\'audit logging sur les lectures de donnees sensibles',
     "L\'audit logging est implemente pour les ecritures (CREATE, UPDATE, DELETE) mais pas "
     "pour les lectures de donnees sensibles. Un utilisateur malveillant peut extraire massivement "
     "des donnees sans laisser de trace dans les journaux d\'audit.",
     "Etendre l\'audit logging aux lectures de donnees sensibles (scores, mesures, rapports "
     "confidentiels). Implementer des alertes sur les volumes de lecture anormaux."),
    ('6.5', 'VULN-22', 'Validation incomplete du schema de projet',
     "Le schema projectSchema dans validators.ts contient une typo : "
     "<font name='DejaVuSans'>'CNCELLED'</font> au lieu de <font name='DejaVuSans'>'CANCELLED'</font> "
     "dans l\'enum status. Cela empeche la creation de projets avec le statut CANCELLED et "
     "peut causer des erreurs silencieuses.",
     "Corriger la typo et ajouter des tests unitaires pour les schemas de validation."),
    ('6.6', 'VULN-23', 'Pas de 2FA pour les comptes a privileges',
     "Les comptes SUPER_ADMIN, DG et DGA n\'ont pas d\'authentification multi-facteurs (2FA). "
     "Ces comptes ont un acces complet a toutes les donnees et fonctionnalites, et leur "
     "compromission aurait un impact catastrophique.",
     "Implementer la 2FA (TOTP ou WebAuthn) pour tous les comptes a privileges eleves. "
     "Rendre la 2FA obligatoire pour les roles SUPER_ADMIN, DG, DGA et DIRECTEUR_TECHNIQUE."),
    ('6.7', 'VULN-24', 'Headers de securite incomplets',
     "Les headers X-Frame-Options, X-Content-Type-Options et Referrer-Policy sont bien "
     "configures, mais il manque Strict-Transport-Security (HSTS), qui est essentiel pour "
     "forcer les connexions HTTPS en production.",
     "Ajouter l\'en-tete Strict-Transport-Security avec une duree d\'au moins 1 an et "
     "l\'option includeSubDomains. Considerer l\'ajout de preload pour une protection maximale."),
    ('6.8', 'VULN-25', 'Pas de politique de retention des donnees personnelles',
     "Les utilisateurs supprimes (soft delete via deletedAt dans l\'ancien schema, ou desactivation "
     "isActive dans le schema actuel) conservent leurs donnees personnelles indefiniment dans "
     "la base de donnees, sans politique de retention ou d\'anonymisation conforme au RGPD.",
     "Implementer une politique de retention et d\'anonymisation des donnees personnelles "
     "conforme au RGPD et a la legislation guineenne sur la protection des donnees."),
    ('6.9', 'VULN-26', 'Absence de tests de securite automatises',
     "Aucun test de securite automatis (SAST, DAST, test d\'intrusion) n\'est configure "
     "dans le pipeline CI/CD. Le fichier package.json ne contient pas de scripts de test.",
     "Integrer des outils SAST (SonarQube, Semgrep), DAST (OWASP ZAP), et des tests de "
     "securite automatises dans le pipeline CI/CD. Ajouter des tests unitaires et d\'integration "
     "pour les mecanismes d\'authentification et d\'autorisation."),
    ('6.10', 'VULN-27', 'Dependance a aws-sdk v2 deprecated',
     "L\'ancien code utilise le package aws-sdk v2 qui est deprecated. Bien que le code actuel "
     "ne semble plus utiliser S3 directement, la presence de cette dependance dans le package.json "
     "cree des vulnerabilites potentielles et augmente la surface d\'attaque.",
     "Supprimer les dependances non utilisees du package.json. Si S3 est necessaire, migrer "
     "vers @aws-sdk/client-s3 v3 qui est le SDK actif."),
]

for num, vid, title, desc, rec in low_vulns:
    story.append(add_heading('%s %s : %s' % (num, vid, title), style_h2))
    story.append(Paragraph(desc, style_body))
    story.append(Paragraph('<b>Recommandation :</b>', style_h3))
    story.append(Paragraph(rec, style_body))

# ═══════════════════════════════════════════════════════════
# SECTION 7: Points positifs
# ═══════════════════════════════════════════════════════════
story.extend(add_major_section('7. Points positifs et bonnes pratiques', style_h1))

story.append(Paragraph(
    "Malgre les vulnerabilites identifiees, la plateforme ONIT-PNG implemente plusieurs "
    "bonnes pratiques de securite qui meritent d\'etre soulignees. Ces elements constituent "
    "une base solide sur laquelle construire les ameliorations recommandees.",
    style_body
))

positives = [
    ("Validation Zod systematique avec stripHtml",
     "Toutes les entrees utilisateur sont validees avec Zod et les tags HTML sont systematiquement "
     "supprimes via la fonction stripHtml, prevenant efficacement les attaques XSS par injection "
     "de balises. Cette approche coherente a travers tous les endpoints est une excellente pratique."),
    ("Systeme RBAC granulaire",
     "L\'implementation d\'un systeme de controle d\'acces base sur les roles avec des permissions "
     "par ressource et action, associe a des politiques d\'acces aux donnees (RLS), est une "
     "architecture solide qui permet un controle fin des acces. Le modele a 9 roles couvre bien "
     "les differents profils d\'utilisation de la plateforme."),
    ("Headers de securite de base",
     "Le middleware configure les en-tetes X-Frame-Options: DENY, X-Content-Type-Options: nosniff, "
     "X-XSS-Protection, Referrer-Policy: strict-origin-when-cross-origin, et Permissions-Policy, "
     "offrant une protection de base contre le clickjacking, le MIME sniffing, et les fuites "
     "de referer."),
    ("Audit logging des actions sensibles",
     "Les actions d\'ecriture (CREATE, UPDATE, DELETE) sont enregistrees dans la table AuditLog "
     "avec l\'utilisateur, l\'action, la ressource, et les details. Ce journal d\'audit est "
     "accessible via un endpoint dedie pour les roles autorises, permettant la traabilite "
     "et le forensic en cas d\'incident."),
    ("Docker securise (build multi-stage, utilisateur non-root)",
     "Le Dockerfile utilise un build multi-stage avec une image finale Alpine, un utilisateur "
     "non-root (nextjs), et un healthcheck. Le docker-compose.yml exige la variable "
     "NEXTAUTH_SECRET via ${NEXTAUTH_SECRET:?}, empechant le demarrage sans secret."),
    ("Configuration Next.js securisee",
     "Le fichier next.config.ts desactive ignoreBuildErrors, active reactStrictMode, supprime "
     "l\'en-tete X-Powered-By, et utilise le mode standalone pour la production. Ce sont des "
     "configurations recommandees par la documentation de securite de Next.js."),
    ("Protection contre les injections SQL via Prisma",
     "L\'utilisation de Prisma ORM avec des requetes parametrees elimine le risque d\'injection "
     "SQL classique. L\'ensemble des requetes utilise les methodes de l\'ORM plutot que du SQL "
     "brut, ce qui est une bonne pratique fondamentale."),
    ("Gestion des sessions JWT avec cookies securises",
     "Les cookies de session sont configures avec httpOnly, sameSite=lax, et secure en production "
     "HTTPS. Le nom du cookie change entre __Secure- et le prefixe normal selon l\'environnement, "
     "et la duree de session est limitee a 8 heures."),
]

for title, desc in positives:
    story.append(add_heading(title, style_h3))
    story.append(Paragraph(desc, style_body))

# ═══════════════════════════════════════════════════════════
# SECTION 8: Plan d'action recommande
# ═══════════════════════════════════════════════════════════
story.extend(add_major_section('8. Plan d\'action recommande', style_h1))

story.append(Paragraph(
    "Le plan d\'action suivant priorise les corrections en fonction de la severite des "
    "vulnerabilites et de l\'impact potentiel sur la securite de la plateforme. Les delais "
    "estimes supposent une equipe de developpement disponible et competent.",
    style_body
))

# Priority table
prio_data = [
    [Paragraph('<b>Priorite</b>', style_th),
     Paragraph('<b>Actions</b>', style_th),
     Paragraph('<b>Vulnerabilites</b>', style_th),
     Paragraph('<b>Delai estime</b>', style_th)],
    [sev_badge('P0 - Urgent', SEV_CRITICAL),
     Paragraph('Changer NEXTAUTH_SECRET, supprimer les credentials du code client, generer des mots de passe uniques', style_td),
     Paragraph('VULN-01, 02, 03', style_td_center),
     Paragraph('24-48h', style_td_center)],
    [sev_badge('P1 - Elevee', SEV_HIGH),
     Paragraph('Corriger le RLS public_only, exiger l\'auth sur les endpoints sensibles, rate limiting persistant, corriger l\'injection contains, proteger les signalements publics', style_td),
     Paragraph('VULN-04, 05, 06, 07, 08', style_td_center),
     Paragraph('1-2 semaines', style_td_center)],
    [sev_badge('P2 - Moyenne', SEV_MEDIUM),
     Paragraph('Migrer vers PostgreSQL, ajouter CSP/CORS, renforcer la validation, audit logging des lectures, corriger les typos, nettoyer les deps', style_td),
     Paragraph('VULN-09 a 17', style_td_center),
     Paragraph('2-4 semaines', style_td_center)],
    [sev_badge('P3 - Faible', SEV_LOW),
     Paragraph('Ajouter 2FA, HSTS, rotation de sessions, tests de securite, politique de retention, endpoint sante, nettoyage auto', style_td),
     Paragraph('VULN-18 a 27', style_td_center),
     Paragraph('1-2 mois', style_td_center)],
]

cw3 = [AVAILABLE_WIDTH * 0.18, AVAILABLE_WIDTH * 0.40, AVAILABLE_WIDTH * 0.22, AVAILABLE_WIDTH * 0.20]
t3 = Table(prio_data, colWidths=cw3, hAlign='CENTER')
t3.setStyle(TableStyle([
    ('BACKGROUND', (0, 0), (-1, 0), TABLE_HEADER_COLOR),
    ('TEXTCOLOR', (0, 0), (-1, 0), TABLE_HEADER_TEXT),
    ('BACKGROUND', (0, 1), (-1, 1), colors.HexColor('#fef2f2')),
    ('BACKGROUND', (0, 2), (-1, 2), colors.HexColor('#fff7ed')),
    ('BACKGROUND', (0, 3), (-1, 3), colors.HexColor('#fefce8')),
    ('BACKGROUND', (0, 4), (-1, 4), colors.HexColor('#f0fdf4')),
    ('GRID', (0, 0), (-1, -1), 0.5, TEXT_MUTED),
    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ('LEFTPADDING', (0, 0), (-1, -1), 6),
    ('RIGHTPADDING', (0, 0), (-1, -1), 6),
    ('TOPPADDING', (0, 0), (-1, -1), 5),
    ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
]))
story.append(Spacer(1, 18))
story.append(t3)
story.append(Spacer(1, 6))
story.append(Paragraph('Tableau 3 : Plan d\'action priorise', ParagraphStyle(
    name='Caption3', fontName=body_font, fontSize=9, alignment=TA_CENTER, textColor=TEXT_MUTED
)))
story.append(Spacer(1, 18))

# ═══════════════════════════════════════════════════════════
# SECTION 9: Matrice de vulnerabilites complete
# ═══════════════════════════════════════════════════════════
story.extend(add_major_section('9. Matrice de vulnerabilites complete', style_h1))

story.append(Paragraph(
    "Le tableau ci-dessous resume l\'ensemble des vulnerabilites identifiees lors de cet audit, "
    "avec leur identification, leur severite, le composant affecte, et la categorie CWE associee. "
    "Cette matrice permet une vue synthetique de l\'ensemble des problemes de securite et facilite "
    "le suivi des corrections.",
    style_body
))

vuln_matrix = [
    ['ID', 'Severite', 'Titre', 'Composant', 'CWE'],
    ['VULN-01', 'CRITIQUE', 'Secret JWT previsible', '.env', 'CWE-321'],
    ['VULN-02', 'CRITIQUE', 'Mot de passe partage (seed)', 'prisma/seed.ts', 'CWE-259'],
    ['VULN-03', 'CRITIQUE', 'Credentials exposes client', 'login-modal.tsx', 'CWE-200'],
    ['VULN-04', 'ELEVEE', 'RLS inefficace public_only', 'src/lib/rbac.ts', 'CWE-863'],
    ['VULN-05', 'ELEVEE', 'Endpoints sans authentification', 'API routes', 'CWE-306'],
    ['VULN-06', 'ELEVEE', 'Rate limiting en memoire', 'middleware.ts', 'CWE-307'],
    ['VULN-07', 'ELEVEE', 'Injection via contains', 'src/lib/rbac.ts', 'CWE-89'],
    ['VULN-08', 'ELEVEE', 'Signalement sans anti-abus', 'alerts/route.ts', 'CWE-799'],
    ['VULN-09', 'MOYENNE', 'SQLite en production', 'schema.prisma', 'CWE-311'],
    ['VULN-10', 'MOYENNE', 'Absence CSP', 'middleware.ts', 'CWE-693'],
    ['VULN-11', 'MOYENNE', 'CORS non configure', 'API routes', 'CWE-942'],
    ['VULN-12', 'MOYENNE', 'Pas de validation mot de passe actuel', 'users/route.ts', 'CWE-620'],
    ['VULN-13', 'MOYENNE', 'Politique mots de passe faible', 'validators.ts', 'CWE-521'],
    ['VULN-14', 'MOYENNE', 'Pas de protection CSRF', 'API routes', 'CWE-352'],
    ['VULN-15', 'MOYENNE', 'Donnees test en production', 'mock-data.ts', 'CWE-489'],
    ['VULN-16', 'MOYENNE', 'Logs trop verbeux', 'API routes', 'CWE-532'],
    ['VULN-17', 'MOYENNE', 'Pas d\'invalidation session', 'auth routes', 'CWE-613'],
    ['VULN-18', 'FAIBLE', 'Pas de rotation sessions JWT', 'auth config', 'CWE-613'],
    ['VULN-19', 'FAIBLE', 'Pas d\'endpoint sante', 'API routes', 'CWE-754'],
    ['VULN-20', 'FAIBLE', 'Pas de nettoyage alertes', 'data model', 'CWE-400'],
    ['VULN-21', 'FAIBLE', 'Pas d\'audit logging lectures', 'rbac.ts', 'CWE-778'],
    ['VULN-22', 'FAIBLE', 'Typo dans validateur', 'validators.ts', 'CWE-20'],
    ['VULN-23', 'FAIBLE', 'Pas de 2FA pour admins', 'auth system', 'CWE-308'],
    ['VULN-24', 'FAIBLE', 'HSTS absent', 'middleware.ts', 'CWE-319'],
    ['VULN-25', 'FAIBLE', 'Pas de retention donnees', 'data model', 'CWE-312'],
    ['VULN-26', 'FAIBLE', 'Pas de tests securite', 'CI/CD', 'CWE-1357'],
    ['VULN-27', 'FAIBLE', 'Dependance aws-sdk v2', 'package.json', 'CWE-1104'],
]

# Build matrix table
matrix_data = []
for i, row in enumerate(vuln_matrix):
    if i == 0:
        matrix_data.append([Paragraph('<b>%s</b>' % cell, style_th) for cell in row])
    else:
        vid, sev, title, comp, cwe = row
        sev_map = {
            'CRITIQUE': SEV_CRITICAL, 'ELEVEE': SEV_HIGH,
            'MOYENNE': SEV_MEDIUM, 'FAIBLE': SEV_LOW
        }
        sev_color = sev_map.get(sev, TEXT_MUTED)
        matrix_data.append([
            Paragraph('<font name="DejaVuSans">%s</font>' % vid, style_td_center),
            Paragraph('<font color="%s"><b>%s</b></font>' % (sev_color.hexval(), sev), style_td_center),
            Paragraph(title, style_td),
            Paragraph('<font name="DejaVuSans">%s</font>' % comp, style_td),
            Paragraph('<font name="DejaVuSans">%s</font>' % cwe, style_td_center),
        ])

cw4 = [AVAILABLE_WIDTH * 0.10, AVAILABLE_WIDTH * 0.14, AVAILABLE_WIDTH * 0.32,
       AVAILABLE_WIDTH * 0.24, AVAILABLE_WIDTH * 0.12]
t4 = Table(matrix_data, colWidths=cw4, hAlign='CENTER', repeatRows=1)

matrix_styles = [
    ('BACKGROUND', (0, 0), (-1, 0), TABLE_HEADER_COLOR),
    ('TEXTCOLOR', (0, 0), (-1, 0), TABLE_HEADER_TEXT),
    ('GRID', (0, 0), (-1, -1), 0.5, TEXT_MUTED),
    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ('LEFTPADDING', (0, 0), (-1, -1), 4),
    ('RIGHTPADDING', (0, 0), (-1, -1), 4),
    ('TOPPADDING', (0, 0), (-1, -1), 4),
    ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
]
for i in range(1, len(matrix_data)):
    bg = TABLE_ROW_EVEN if i % 2 == 1 else TABLE_ROW_ODD
    matrix_styles.append(('BACKGROUND', (0, i), (-1, i), bg))

t4.setStyle(TableStyle(matrix_styles))
story.append(Spacer(1, 12))
story.append(t4)
story.append(Spacer(1, 6))
story.append(Paragraph('Tableau 4 : Matrice complete des vulnerabilites identifiees', ParagraphStyle(
    name='Caption4', fontName=body_font, fontSize=9, alignment=TA_CENTER, textColor=TEXT_MUTED
)))

# ═══════════════════════════════════════════════════════════
# SECTION 10: Conclusion
# ═══════════════════════════════════════════════════════════
story.extend(add_major_section('10. Conclusion et perspectives', style_h1))

story.append(Paragraph(
    "La plateforme ONIT-PNG presente une architecture de securite globalement coherente avec "
    "des fondements solides, notamment le systeme RBAC granulaire, la validation systematique "
    "des entrees via Zod avec stripHtml, les headers de securite de base, et l\'audit logging "
    "des ecritures. Ces elements temoignent d\'une reflexion serieuse sur la securite des "
    "le stade de la conception.",
    style_body
))
story.append(Paragraph(
    "Cependant, l\'audit revele plusieurs vulnerabilites critiques qui necessitent une action "
    "immediate, en particulier la gestion des secrets cryptographiques, l\'exposition de "
    "credentials dans le code client, et les lacunes du systeme de controle d\'acces pour "
    "les utilisateurs non authentifies. Ces problemes, s\'ils sont exploites, pourraient "
    "compromettre l\'integrite de la plateforme et la confidentialite des donnees sensibles "
    "de telecommunications qu\'elle gere pour le compte de l\'ARPT.",
    style_body
))
story.append(Paragraph(
    "La migration vers PostgreSQL est un prealable indispensable pour un deploiement en "
    "production, tant pour des raisons de performance et de fiabilite que de securite "
    "(chiffrement au repos, connexions securisees, sauvegardes). L\'ajout d\'un CSP, "
    "du HSTS, et de mecanismes de protection anti-abus completera la posture de securite "
    "de l\'application.",
    style_body
))
story.append(Paragraph(
    "En suivant le plan d\'action recommande, en commencant par les corrections P0 (24-48h) "
    "et P1 (1-2 semaines), la plateforme peut atteindre un niveau de securite acceptable "
    "pour un deploiement en production. Un audit de penetration externe est recommande "
    "apres la mise en oeuvre des corrections pour valider l\'efficacite des mesures "
    "implementees.",
    style_body
))

# ─── Build the body PDF ───
doc.multiBuild(story, onLaterPages=add_page_number, onFirstPage=add_page_number)
print(f"Body PDF generated: {body_path}")

# ───────────────────────────────────────────────────────────
# Generate Cover Page (HTML/Playwright via html2poster.js)
# ───────────────────────────────────────────────────────────
cover_html_path = '/home/z/my-project/download/_audit_cover.html'
cover_pdf_path = '/home/z/my-project/download/_audit_cover.pdf'

cover_html = """<!DOCTYPE html>
<html lang="fr">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600;700;800;900&display=swap" rel="stylesheet">
<style>
  @page { size: 794px 1123px; margin: 0; }
  * { box-sizing: border-box; margin: 0; padding: 0; }
  html, body {
    width: 794px; height: 1123px;
    margin: 0; padding: 0;
    font-family: 'Inter', sans-serif;
    background: #ffffff;
    color: #1f2122;
    overflow: hidden;
  }
  .cover {
    position: relative;
    width: 794px;
    height: 1123px;
  }
  /* Layer 1: Background */
  .bg-layer {
    position: absolute; inset: 0;
    overflow: hidden; z-index: 1;
  }
  .sidebar {
    position: absolute; left: 0; top: 0;
    width: 79px; height: 1123px;
    background: #4927b0;
  }
  .sidebar-watermark {
    position: absolute;
    left: 50%; top: 50%;
    transform: translate(-50%, -50%) rotate(-90deg);
    font-size: 48px; font-weight: 900;
    color: rgba(255,255,255,0.12);
    letter-spacing: 6px;
    white-space: nowrap;
  }
  /* Layer 2: Structure lines */
  .struct-layer {
    position: absolute; inset: 0;
    z-index: 2;
  }
  .bottom-line {
    position: absolute;
    bottom: 100px; left: 119px; right: 60px;
    height: 1px;
    background: rgba(73,39,176,0.25);
  }
  /* Layer 3: Content */
  .content-layer {
    position: absolute; inset: 0;
    z-index: 3;
    padding-left: 119px;
    padding-right: 60px;
  }
  .kicker {
    position: absolute;
    top: 200px; left: 119px;
    font-size: 13px; font-weight: 400;
    letter-spacing: 4px; text-transform: uppercase;
    color: rgba(31,33,34,0.55);
  }
  .hero-title {
    position: absolute;
    top: 260px; left: 119px; right: 60px;
    font-size: 42px; font-weight: 900;
    line-height: 1.15;
    color: #1f2122;
    max-width: 550px;
  }
  .summary {
    position: absolute;
    top: 460px; left: 119px;
    max-width: 460px;
    font-size: 16px; font-weight: 400;
    line-height: 1.65;
    color: rgba(31,33,34,0.80);
  }
  .meta-group {
    position: absolute;
    top: 640px; left: 119px;
  }
  .meta-label {
    font-size: 11px; font-weight: 600;
    letter-spacing: 2px; text-transform: uppercase;
    color: rgba(73,39,176,0.7);
    margin-bottom: 4px;
  }
  .meta-value {
    font-size: 16px; font-weight: 400;
    color: #1f2122;
    margin-bottom: 18px;
  }
  .footer-left {
    position: absolute;
    bottom: 70px; left: 119px;
    font-size: 12px; color: rgba(31,33,34,0.5);
  }
  .footer-right {
    position: absolute;
    bottom: 70px; right: 60px;
    font-size: 12px; font-weight: 600;
    color: rgba(73,39,176,0.6);
    letter-spacing: 2px;
  }
  @media screen {
    html { transform-origin: 0 0; }
  }
</style>
</head>
<body>
<div class="cover">
  <!-- Layer 1: Background -->
  <div class="bg-layer">
    <div class="sidebar">
      <div class="sidebar-watermark">AUDIT</div>
    </div>
  </div>
  <!-- Layer 2: Structure -->
  <div class="struct-layer">
    <div class="bottom-line"></div>
  </div>
  <!-- Layer 3: Content -->
  <div class="content-layer">
    <div class="kicker">Rapport d'audit de securite</div>
    <div class="hero-title">ONIT-PNG<br/>Observatoire National Intelligent<br/>des Telecommunications</div>
    <div class="summary">
      Audit complet de securite de la plateforme ONIT-PNG, couvrant l'authentification, le controle d'acces RBAC, les API, la configuration infrastructure et les composants frontend. 27 vulnerabilites identifiees avec plan d'action priorise.
    </div>
    <div class="meta-group">
      <div class="meta-label">Organisation</div>
      <div class="meta-value">ARPT - Autorite de Regulation des Postes et Telecommunications</div>
      <div class="meta-label">Date</div>
      <div class="meta-value">17 mai 2026</div>
      <div class="meta-label">Classification</div>
      <div class="meta-value">Confidentiel</div>
      <div class="meta-label">Version</div>
      <div class="meta-value">1.0</div>
    </div>
    <div class="footer-left">Republique de Guinee</div>
    <div class="footer-right">Z.AI SECURITY AUDIT</div>
  </div>
</div>
</body>
</html>
"""

with open(cover_html_path, 'w', encoding='utf-8') as f:
    f.write(cover_html)
print(f"Cover HTML generated: {cover_html_path}")

# ───────────────────────────────────────────────────────────
# Render cover and merge
# ───────────────────────────────────────────────────────────
import subprocess

scripts_dir = os.path.join(os.path.expanduser('~'), 'my-project', 'skills', 'pdf', 'scripts')

# Validate cover HTML
try:
    result = subprocess.run(
        ['python3', os.path.join(scripts_dir, 'poster_validate.py'), 'check-html', cover_html_path],
        capture_output=True, text=True, timeout=30
    )
    print("Cover validation:", result.stdout[:500] if result.stdout else "OK")
    if result.stderr:
        print("Cover validation stderr:", result.stderr[:300])
except Exception as e:
    print(f"Cover validation skipped: {e}")

# Render cover PDF via html2poster.js
try:
    result = subprocess.run(
        ['node', os.path.join(scripts_dir, 'html2poster.js'),
         cover_html_path, '--output', cover_pdf_path, '--width', '794px'],
        capture_output=True, text=True, timeout=60
    )
    print("Cover render:", "SUCCESS" if result.returncode == 0 else f"FAILED: {result.stderr[:300]}")
except Exception as e:
    print(f"Cover render error: {e}")
    cover_pdf_path = None

# Merge cover + body into final PDF
from pypdf import PdfReader, PdfWriter, Transformation

A4_W, A4_H = 595.28, 841.89

def normalize_page_to_a4(page):
    box = page.mediabox
    w, h = float(box.width), float(box.height)
    if abs(w - A4_W) > 2 or abs(h - A4_H) > 2:
        sx, sy = A4_W / w, A4_H / h
        page.add_transformation(Transformation().scale(sx=sx, sy=sy))
        page.mediabox.lower_left = (0, 0)
        page.mediabox.upper_right = (A4_W, A4_H)
    return page

writer = PdfWriter()

if cover_pdf_path and os.path.exists(cover_pdf_path):
    cover_page = PdfReader(cover_pdf_path).pages[0]
    writer.add_page(normalize_page_to_a4(cover_page))
    print("Cover page added")
else:
    print("WARNING: No cover page, body-only PDF")

for page in PdfReader(body_path).pages:
    writer.add_page(normalize_page_to_a4(page))

writer.add_metadata({
    '/Title': 'ONIT-PNG Audit de Securite - Rapport Complet',
    '/Author': 'Z.ai',
    '/Creator': 'Z.ai',
    '/Subject': 'Audit de securite de la plateforme ONIT-PNG pour ARPT Guinee',
})

with open(output_path, 'wb') as f:
    writer.write(f)

print(f"\nFinal PDF generated: {output_path}")
print(f"File size: {os.path.getsize(output_path) / 1024:.1f} KB")

# Cleanup temp files
for tmp in [body_path, cover_html_path, cover_pdf_path]:
    try:
        if os.path.exists(tmp):
            os.remove(tmp)
    except:
        pass
