#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
ONIT-PNG Document Generator
Plateforme de l'Observatoire National Intelligent des Télécommunications - République de Guinée
"""

import sys, os, hashlib
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch, cm
from reportlab.lib import colors
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_JUSTIFY, TA_RIGHT
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    PageBreak, KeepTogether, CondPageBreak, Image
)
from reportlab.platypus.tableofcontents import TableOfContents
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase.pdfmetrics import registerFontFamily

# ━━ Color Palette (auto-generated by pdf.py palette.generate) ━━
# Intent: nature | Mode: minimal | Harmony: analogous
ACCENT       = colors.HexColor('#1a9898')
TEXT_PRIMARY  = colors.HexColor('#1e1f21')
TEXT_MUTED    = colors.HexColor('#7d8289')
BG_SURFACE   = colors.HexColor('#d7dadf')
BG_PAGE      = colors.HexColor('#e8ebee')

# ReportLab table colors
TABLE_HEADER_COLOR = ACCENT
TABLE_HEADER_TEXT  = colors.white
TABLE_ROW_EVEN     = colors.white
TABLE_ROW_ODD      = BG_SURFACE

# ━━ Font Registration ━━
pdfmetrics.registerFont(TTFont('Microsoft YaHei', '/usr/share/fonts/truetype/chinese/msyh.ttf'))
pdfmetrics.registerFont(TTFont('SimHei', '/usr/share/fonts/truetype/chinese/SimHei.ttf'))
pdfmetrics.registerFont(TTFont('SarasaMonoSC', '/usr/share/fonts/truetype/chinese/SarasaMonoSC-Regular.ttf'))
pdfmetrics.registerFont(TTFont('Times New Roman', '/usr/share/fonts/truetype/english/Times-New-Roman.ttf'))
pdfmetrics.registerFont(TTFont('Calibri', '/usr/share/fonts/truetype/english/calibri-regular.ttf'))
pdfmetrics.registerFont(TTFont('DejaVuSans', '/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf'))

registerFontFamily('Times New Roman', normal='Times New Roman', bold='Times New Roman')
registerFontFamily('SimHei', normal='SimHei', bold='SimHei')
registerFontFamily('Calibri', normal='Calibri', bold='Calibri')
registerFontFamily('DejaVuSans', normal='DejaVuSans', bold='DejaVuSans')

# Install font fallback for mixed CJK/Latin
sys.path.insert(0, os.path.join(os.path.expanduser('~'), 'my-project/skills/pdf/scripts'))
from pdf import install_font_fallback
install_font_fallback()

# ━━ Page Setup ━━
PAGE_W, PAGE_H = A4
LEFT_MARGIN = 1.0 * inch
RIGHT_MARGIN = 1.0 * inch
TOP_MARGIN = 0.8 * inch
BOTTOM_MARGIN = 0.8 * inch
AVAILABLE_WIDTH = PAGE_W - LEFT_MARGIN - RIGHT_MARGIN

# ━━ Style Definitions ━━
styles = getSampleStyleSheet()

# Title style
title_style = ParagraphStyle(
    name='DocTitle', fontName='Times New Roman', fontSize=22, leading=28,
    textColor=ACCENT, spaceAfter=12, spaceBefore=6, alignment=TA_LEFT
)

# H1 style
h1_style = ParagraphStyle(
    name='H1', fontName='Times New Roman', fontSize=18, leading=24,
    textColor=ACCENT, spaceAfter=10, spaceBefore=18, alignment=TA_LEFT
)

# H2 style
h2_style = ParagraphStyle(
    name='H2', fontName='Times New Roman', fontSize=14, leading=20,
    textColor=TEXT_PRIMARY, spaceAfter=8, spaceBefore=14, alignment=TA_LEFT
)

# H3 style
h3_style = ParagraphStyle(
    name='H3', fontName='Times New Roman', fontSize=12, leading=17,
    textColor=TEXT_PRIMARY, spaceAfter=6, spaceBefore=10, alignment=TA_LEFT
)

# Body text style
body_style = ParagraphStyle(
    name='Body', fontName='Times New Roman', fontSize=10.5, leading=17,
    textColor=TEXT_PRIMARY, spaceAfter=6, spaceBefore=0, alignment=TA_JUSTIFY,
    firstLineIndent=0
)

# Body indent style
body_indent_style = ParagraphStyle(
    name='BodyIndent', fontName='Times New Roman', fontSize=10.5, leading=17,
    textColor=TEXT_PRIMARY, spaceAfter=6, spaceBefore=0, alignment=TA_JUSTIFY,
    leftIndent=20
)

# Bullet style
bullet_style = ParagraphStyle(
    name='Bullet', fontName='Times New Roman', fontSize=10.5, leading=17,
    textColor=TEXT_PRIMARY, spaceAfter=4, spaceBefore=0, alignment=TA_LEFT,
    leftIndent=20, bulletIndent=8
)

# Table header style
tbl_header_style = ParagraphStyle(
    name='TblHeader', fontName='Times New Roman', fontSize=10, leading=14,
    textColor=TABLE_HEADER_TEXT, alignment=TA_CENTER
)

# Table cell style
tbl_cell_style = ParagraphStyle(
    name='TblCell', fontName='Times New Roman', fontSize=9.5, leading=14,
    textColor=TEXT_PRIMARY, alignment=TA_LEFT, wordWrap='CJK'
)

tbl_cell_center_style = ParagraphStyle(
    name='TblCellCenter', fontName='Times New Roman', fontSize=9.5, leading=14,
    textColor=TEXT_PRIMARY, alignment=TA_CENTER
)

# Caption style
caption_style = ParagraphStyle(
    name='Caption', fontName='Times New Roman', fontSize=9, leading=13,
    textColor=TEXT_MUTED, alignment=TA_CENTER, spaceAfter=6, spaceBefore=3
)

# Callout box style
callout_style = ParagraphStyle(
    name='Callout', fontName='Times New Roman', fontSize=10.5, leading=17,
    textColor=ACCENT, spaceAfter=6, spaceBefore=6, alignment=TA_LEFT,
    leftIndent=24, borderColor=ACCENT, borderWidth=2, borderPadding=8,
    backColor=colors.HexColor('#f0fafa')
)

# Muted text style
muted_style = ParagraphStyle(
    name='Muted', fontName='Times New Roman', fontSize=9, leading=13,
    textColor=TEXT_MUTED, alignment=TA_LEFT, spaceAfter=4
)

# ━━ Helper Functions ━━
MAX_KEEP_HEIGHT = PAGE_H * 0.4

def safe_keep_together(elements):
    total_h = 0
    for el in elements:
        w, h = el.wrap(AVAILABLE_WIDTH, PAGE_H)
        total_h += h
    if total_h <= MAX_KEEP_HEIGHT:
        return [KeepTogether(elements)]
    elif len(elements) >= 2:
        return [KeepTogether(elements[:2])] + list(elements[2:])
    else:
        return list(elements)

def make_table(data, col_widths, caption_text=None):
    """Create a styled table with caption."""
    table = Table(data, colWidths=col_widths, hAlign='CENTER')
    style_commands = [
        ('BACKGROUND', (0, 0), (-1, 0), TABLE_HEADER_COLOR),
        ('TEXTCOLOR', (0, 0), (-1, 0), TABLE_HEADER_TEXT),
        ('GRID', (0, 0), (-1, -1), 0.5, TEXT_MUTED),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('LEFTPADDING', (0, 0), (-1, -1), 8),
        ('RIGHTPADDING', (0, 0), (-1, -1), 8),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
    ]
    # Alternating row colors
    for i in range(1, len(data)):
        bg = TABLE_ROW_EVEN if i % 2 == 1 else TABLE_ROW_ODD
        style_commands.append(('BACKGROUND', (0, i), (-1, i), bg))
    table.setStyle(TableStyle(style_commands))
    
    elements = [Spacer(1, 18), table]
    if caption_text:
        elements.append(Spacer(1, 6))
        elements.append(Paragraph(caption_text, caption_style))
    elements.append(Spacer(1, 18))
    return elements

# ━━ TOC DocTemplate ━━
class TocDocTemplate(SimpleDocTemplate):
    def afterFlowable(self, flowable):
        if hasattr(flowable, 'bookmark_name'):
            level = getattr(flowable, 'bookmark_level', 0)
            text = getattr(flowable, 'bookmark_text', '')
            key = getattr(flowable, 'bookmark_key', '')
            self.notify('TOCEntry', (level, text, self.page, key))

def add_heading(text, style, level=0):
    key = 'h_%s' % hashlib.md5(text.encode()).hexdigest()[:8]
    p = Paragraph('<a name="%s"/>%s' % (key, text), style)
    p.bookmark_name = text
    p.bookmark_level = level
    p.bookmark_text = text
    p.bookmark_key = key
    return p

H1_ORPHAN_THRESHOLD = (PAGE_H - TOP_MARGIN - BOTTOM_MARGIN) * 0.15

def add_major_section(text, style):
    return [
        CondPageBreak(H1_ORPHAN_THRESHOLD),
        add_heading(text, style, level=0),
    ]

# ━━ Build Document ━━
output_path = '/home/z/my-project/download/ONIT-PNG_Guide_Fonctionnement.pdf'

doc = TocDocTemplate(
    output_path,
    pagesize=A4,
    leftMargin=LEFT_MARGIN,
    rightMargin=RIGHT_MARGIN,
    topMargin=TOP_MARGIN,
    bottomMargin=BOTTOM_MARGIN,
    title='ONIT-PNG - Guide de Fonctionnement et Collecte des Donnees',
    author='ARPT - Autorite de Regulation des Postes et Telecommunications',
    creator='Z.ai',
)

story = []

# ━━ TABLE OF CONTENTS ━━
toc = TableOfContents()
toc.levelStyles = [
    ParagraphStyle(name='TOCLevel0', fontName='Times New Roman', fontSize=13, leading=20, leftIndent=20, spaceBefore=8, spaceAfter=4, textColor=ACCENT),
    ParagraphStyle(name='TOCLevel1', fontName='Times New Roman', fontSize=11, leading=17, leftIndent=40, spaceBefore=4, spaceAfter=2, textColor=TEXT_PRIMARY),
]

story.append(Paragraph('<b>Table des Matieres</b>', title_style))
story.append(Spacer(1, 12))
story.append(toc)
story.append(PageBreak())

# ═══════════════════════════════════════════════════════════
# SECTION 1: Présentation Générale
# ═══════════════════════════════════════════════════════════
story.extend(add_major_section('<b>1. Presentation Generale de la Solution ONIT-PNG</b>', h1_style))

story.append(Paragraph(
    "L'Observatoire National Intelligent des Telecommunications de la Republique de Guinee (ONIT-PNG) est une plateforme numerique "
    "de supervision et de regulation des telecommunications developpee pour le compte de l'Autorite de Regulation des Postes et "
    "Telecommunications (ARPT). Cette solution offre une vision strategique et operationnelle de la qualite des services de "
    "telecommunications sur l'ensemble du territoire national, permettant aux decideurs de suivre en temps reel les indicateurs "
    "cles de performance des operateurs, de detecter les zones de degradation, et de prendre des decisions eclairees basees sur "
    "des donnees factuelles.",
    body_style
))

story.append(Paragraph(
    "La plateforme ONIT-PNG repose sur une architecture moderne basee sur les technologies web de derniere generation : "
    "Next.js 16 avec le App Router, TypeScript pour la robustesse du code, Prisma ORM pour l'acces aux donnees, et Leaflet "
    "pour la cartographie interactive. Le systeme integre un mecanisme complet de controle d'acces base sur les roles (RBAC) "
    "et une securite au niveau des lignes de donnees (Row-Level Security), garantissant que chaque utilisateur n'accede qu'aux "
    "informations pertinentes pour son niveau d'autorisation. Le design suit une esthetique gouvernementale avec un theme sombre "
    "bleu nuit et des accents dores, utilisant le glassmorphisme pour une interface moderne et professionnelle.",
    body_style
))

story.append(Spacer(1, 8))

story.append(add_heading('<b>1.1 Objectifs Strategiques</b>', h2_style, level=1))

story.append(Paragraph(
    "La plateforme ONIT-PNG poursuit plusieurs objectifs strategiques essentiels a la mission de regulation de l'ARPT. "
    "Premierement, elle vise a fournir une transparence totale sur la qualite des services de telecommunications en Guinee, "
    "en permettant le suivi en temps reel des metriques de performance des trois operateurs nationaux (Orange Guinee, "
    "MTN Guinee et Celcom Guinee) a travers les huit regions administratives du pays.",
    body_style
))

story.append(Paragraph(
    "Deuxiemement, la plateforme automatise le processus de scoring des operateurs en calculant des scores composites "
    "trimestriels couvrant la couverture reseau, la qualite de service, la qualite d'experience et la conformite reglementaire. "
    "Ces scores permettent une comparaison objective et quantifiee des performances de chaque operateur, facilitant les "
    "decisions reglementaires et les sanctions eventuelles.",
    body_style
))

story.append(Paragraph(
    "Troisiemement, ONIT-PNG offre un portail citoyen permettant aux usagers de signaler directement les problemes de "
    "telecommunications qu'ils rencontrent, creant ainsi un canal de feedback en temps reel entre la population et le "
    "regulateur. Enfin, la plateforme genere des rapports reglementaires, operationnels et publics de maniere automatisee, "
    "facilitant la communication institutionnelle et le suivi des obligations des operateurs.",
    body_style
))

# Key metrics table
story.append(Spacer(1, 8))
story.append(add_heading('<b>1.2 Chiffres Cles de la Plateforme</b>', h2_style, level=1))

key_data = [
    [Paragraph('<b>Indicateur</b>', tbl_header_style), Paragraph('<b>Valeur</b>', tbl_header_style), Paragraph('<b>Description</b>', tbl_header_style)],
    [Paragraph('Operateurs surveilles', tbl_cell_style), Paragraph('3', tbl_cell_center_style), Paragraph('Orange Guinee, MTN Guinee, Celcom Guinee', tbl_cell_style)],
    [Paragraph('Regions couvertes', tbl_cell_style), Paragraph('8', tbl_cell_center_style), Paragraph('Conakry, Kindia, Boke, Labe, Mamou, Faranah, Kankan, Nzerekore', tbl_cell_style)],
    [Paragraph('Mesures QoS', tbl_cell_style), Paragraph('78+', tbl_cell_center_style), Paragraph('Metriques RF, reseau, internet et QoE collectees', tbl_cell_style)],
    [Paragraph('Scores operateurs', tbl_cell_style), Paragraph('12', tbl_cell_center_style), Paragraph('4 trimestres x 3 operateurs', tbl_cell_style)],
    [Paragraph('Roles utilisateurs', tbl_cell_style), Paragraph('9', tbl_cell_center_style), Paragraph('De SUPER_ADMIN a PUBLIC', tbl_cell_style)],
    [Paragraph('Permissions', tbl_cell_style), Paragraph('80+', tbl_cell_center_style), Paragraph('Regles d\'acces granulaires resource:action', tbl_cell_style)],
    [Paragraph('Politiques RLS', tbl_cell_style), Paragraph('18', tbl_cell_center_style), Paragraph('Filtrage au niveau des lignes de donnees', tbl_cell_style)],
    [Paragraph('Points API', tbl_cell_style), Paragraph('10+', tbl_cell_center_style), Paragraph('Endpoints REST securises', tbl_cell_style)],
    [Paragraph('Comptes utilisateurs', tbl_cell_style), Paragraph('10', tbl_cell_center_style), Paragraph('ARPT (7), Orange (1), MTN (1), Celcom (1)', tbl_cell_style)],
]

col_w = [AVAILABLE_WIDTH * 0.25, AVAILABLE_WIDTH * 0.12, AVAILABLE_WIDTH * 0.63]
story.extend(make_table(key_data, col_w, 'Tableau 1 : Chiffres cles de la plateforme ONIT-PNG'))


# ═══════════════════════════════════════════════════════════
# SECTION 2: Architecture Technique
# ═══════════════════════════════════════════════════════════
story.extend(add_major_section('<b>2. Architecture Technique de la Plateforme</b>', h1_style))

story.append(Paragraph(
    "L'architecture technique de ONIT-PNG est concue pour repondre aux exigences d'une plateforme gouvernementale : "
    "fiabilite, securite, evolutivite et maintenabilite. Le choix de Next.js 16 avec le App Router permet de beneficier "
    "du rendu cote serveur (SSR) pour les pages publiques, de l'API Routes integree pour les endpoints backend, et du "
    "Turbopack pour un developpement rapide. L'ensemble de la logique applicative est contenu dans un seul projet, "
    "facilitant le deploiement et la maintenance.",
    body_style
))

story.append(add_heading('<b>2.1 Stack Technologique</b>', h2_style, level=1))

tech_data = [
    [Paragraph('<b>Couche</b>', tbl_header_style), Paragraph('<b>Technologie</b>', tbl_header_style), Paragraph('<b>Role</b>', tbl_header_style)],
    [Paragraph('Framework', tbl_cell_style), Paragraph('Next.js 16 (App Router)', tbl_cell_style), Paragraph('Framework fullstack avec SSR, API Routes, et Turbopack', tbl_cell_style)],
    [Paragraph('Langage', tbl_cell_style), Paragraph('TypeScript', tbl_cell_style), Paragraph('Typage statique pour la robustesse du code', tbl_cell_style)],
    [Paragraph('Base de donnees', tbl_cell_style), Paragraph('SQLite via Prisma ORM', tbl_cell_style), Paragraph('Stockage relationnel avec ORM type-safe', tbl_cell_style)],
    [Paragraph('Authentification', tbl_cell_style), Paragraph('NextAuth.js v4 (JWT)', tbl_cell_style), Paragraph('Authentification par credentials avec tokens JWT', tbl_cell_style)],
    [Paragraph('Hashage', tbl_cell_style), Paragraph('bcryptjs', tbl_cell_style), Paragraph('Hachage securise des mots de passe', tbl_cell_style)],
    [Paragraph('UI', tbl_cell_style), Paragraph('React + TailwindCSS 4 + shadcn/ui', tbl_cell_style), Paragraph('Interface utilisateur responsive avec design system', tbl_cell_style)],
    [Paragraph('Cartographie', tbl_cell_style), Paragraph('Leaflet (import dynamique)', tbl_cell_style), Paragraph('Carte interactive de la Guinee avec GeoJSON', tbl_cell_style)],
    [Paragraph('Notifications', tbl_cell_style), Paragraph('Sonner (toast)', tbl_cell_style), Paragraph('Notifications en temps reel dans l\'interface', tbl_cell_style)],
]

col_w2 = [AVAILABLE_WIDTH * 0.18, AVAILABLE_WIDTH * 0.32, AVAILABLE_WIDTH * 0.50]
story.extend(make_table(tech_data, col_w2, 'Tableau 2 : Stack technologique de la plateforme'))

story.append(add_heading('<b>2.2 Architecture des Composants</b>', h2_style, level=1))

story.append(Paragraph(
    "La plateforme est organisee en modules fonctionnels independants, chacun correspondant a un onglet du tableau de bord. "
    "Cette architecture modulaire permet d'ajouter ou de modifier des fonctionnalites sans impacter les autres modules. "
    "Le composant principal OnitLayout gere la navigation laterale et le rendu conditionnel des modules en fonction du "
    "role de l'utilisateur connecte. Chaque module communique avec les API backend via des appels fetch securises, "
    "et les donnees sont filtree cote serveur selon les politiques RLS du role de l'utilisateur.",
    body_style
))

story.append(Paragraph(
    "Le client Prisma utilise le pattern singleton pour eviter l'epuisement des connexions en mode developpement. "
    "Les sessions utilisateur sont gerees via des tokens JWT d'une duree maximale de 8 heures, avec les informations "
    "de role et de permissions embarquees dans le token. Chaque connexion genere une entree dans le journal d'audit, "
    "assurant la tracabilite complete des acces.",
    body_style
))


# ═══════════════════════════════════════════════════════════
# SECTION 3: Collecte et Flux des Données
# ═══════════════════════════════════════════════════════════
story.extend(add_major_section('<b>3. Collecte et Flux des Donnees</b>', h1_style))

story.append(Paragraph(
    "Le coeur de la plateforme ONIT-PNG repose sur la collecte, le traitement et la presentation des donnees de qualite "
    "de service. Comprendre comment les informations sont collectees et transformees est essentiel pour apprecier la "
    "fiabilite et la pertinence des indicateurs presentes aux decideurs. Le systeme de collecte s'articule autour de "
    "cinq sources principales, chacune correspondant a un canal d'acquisition specifique.",
    body_style
))

story.append(add_heading('<b>3.1 Sources de Collecte des Donnees</b>', h2_style, level=1))

story.append(add_heading('<b>3.1.1 Campagnes d\'Audit Terrain (Drive Test / Walk Test)</b>', h3_style, level=1))

story.append(Paragraph(
    "La source principale de donnees de la plateforme est constituee par les campagnes d'audit terrain menees par les "
    "equipes de l'ARPT. Ces campagnes consistent a deployer des equipements de mesure mobiles dans les zones cibles "
    "pour collecter des donnees reelles sur la qualite du signal et des services. Il existe quatre types de campagnes "
    "distinctes, chacune adaptee a un contexte de mesure specifique.",
    body_style
))

story.append(Paragraph(
    "Les Drive Tests sont effectues a bord de vehicules equipes de sondes de mesure qui parcourent les axes routiers "
    "et les zones periurbaines. Ils permettent de cartographier la couverture reseau le long des corridors de transport "
    "et de detecter les zones blanches entre les sites. Les Walk Tests sont realises par des operateurs a pied, "
    "generalement dans les zones urbaines denses ou les batiments, pour mesurer la penetration du signal a l'interieur. "
    "Les campagnes QoS Internet evaluent specifiquement la qualite de la connexion de donnees (debit, latence, DNS), "
    "tandis que les campagnes QoS Mobile se concentrent sur la qualite des appels vocaux (taux de reussite, drop calls).",
    body_style
))

campaign_data = [
    [Paragraph('<b>Type de Campagne</b>', tbl_header_style), Paragraph('<b>Code</b>', tbl_header_style), Paragraph('<b>Metriques Collectees</b>', tbl_header_style), Paragraph('<b>Contexte</b>', tbl_header_style)],
    [Paragraph('Drive Test', tbl_cell_style), Paragraph('DRIVE_TEST', tbl_cell_center_style), Paragraph('RSSI, RSRP, RSRQ, SINR, couverture', tbl_cell_style), Paragraph('Corridors routiers, zones periurbaines', tbl_cell_style)],
    [Paragraph('Walk Test', tbl_cell_style), Paragraph('WALK_TEST', tbl_cell_center_style), Paragraph('RSSI, RSRP, RSRQ, SINR, penetration', tbl_cell_style), Paragraph('Zones urbaines denses, interieurs', tbl_cell_style)],
    [Paragraph('QoS Internet', tbl_cell_style), Paragraph('QOS_INTERNET', tbl_cell_center_style), Paragraph('Debit, latence, ping, DNS, TCP', tbl_cell_style), Paragraph('Evaluation connexion de donnees', tbl_cell_style)],
    [Paragraph('QoS Mobile', tbl_cell_style), Paragraph('QOS_MOBILE', tbl_cell_center_style), Paragraph('Taux appel reussi, drop call, gigue', tbl_cell_style), Paragraph('Evaluation appels vocaux', tbl_cell_style)],
]

col_w3 = [AVAILABLE_WIDTH * 0.20, AVAILABLE_WIDTH * 0.15, AVAILABLE_WIDTH * 0.35, AVAILABLE_WIDTH * 0.30]
story.extend(make_table(campaign_data, col_w3, 'Tableau 3 : Types de campagnes d\'audit terrain'))

story.append(add_heading('<b>3.1.2 Metriques de Qualite de Service (MesureQoS)</b>', h3_style, level=1))

story.append(Paragraph(
    "Chaque mesure realisee lors d'une campagne d'audit est enregistree dans la base de donnees sous la forme d'un "
    "enregistrement MesureQoS. Ce modele constitue le coeur du systeme de donnees et capture quatre categories de "
    "metriques complementaires, permettant une evaluation complete de la performance reseau a un point de mesure "
    "donne, a un instant donne, pour un operateur et une region specifies.",
    body_style
))

metrics_data = [
    [Paragraph('<b>Categorie</b>', tbl_header_style), Paragraph('<b>Metriques</b>', tbl_header_style), Paragraph('<b>Unite / Plage</b>', tbl_header_style)],
    [Paragraph('Radio Frequence (RF)', tbl_cell_style), Paragraph('RSSI, RSRP, RSRQ, SINR', tbl_cell_style), Paragraph('dBm, dB', tbl_cell_style)],
    [Paragraph('Reseau Mobile', tbl_cell_style), Paragraph('Latence, debit descendant/montant, gigue, taux appel reussi, taux drop call', tbl_cell_style), Paragraph('ms, Mbps, %, %', tbl_cell_style)],
    [Paragraph('Internet', tbl_cell_style), Paragraph('Debit download/upload, ping, DNS lookup, TCP connect', tbl_cell_style), Paragraph('Mbps, ms, ms, ms', tbl_cell_style)],
    [Paragraph('QoE (Experience)', tbl_cell_style), Paragraph('Score QoE, page load time, video buffering', tbl_cell_style), Paragraph('0-100, s, %', tbl_cell_style)],
]

col_w4 = [AVAILABLE_WIDTH * 0.22, AVAILABLE_WIDTH * 0.48, AVAILABLE_WIDTH * 0.30]
story.extend(make_table(metrics_data, col_w4, 'Tableau 4 : Categories de metriques collectees par point de mesure'))

story.append(Paragraph(
    "Les metriques RF (RSSI, RSRP, RSRQ, SINR) mesurent la qualite du signal radio recu par le terminal. Le RSRP "
    "(Reference Signal Received Power) indique la puissance du signal de reference, typiquement entre -140 dBm (aucun "
    "signal) et -44 dBm (signal excellent). Le SINR (Signal to Interference plus Noise Ratio) mesure le rapport entre "
    "le signal utile et les interférences, determinant directement le debit achievable. Les metriques reseau evaluent "
    "les performances des services : la latence mesure le temps d'aller-retour d'un paquet, le debit descendant et "
    "montant quantifient la bande passante disponible, et les taux d'appel reussi et de drop call evaluent la "
    "fiabilite de la voix. Les metriques Internet se concentrent sur l'experience de navigation et de telechargement, "
    "tandis que les metriques QoE synthetisent l'experience utilisateur globale.",
    body_style
))

story.append(add_heading('<b>3.1.3 Signalements Citoyens (Alertes Publiques)</b>', h3_style, level=1))

story.append(Paragraph(
    "La plateforme integre un mecanisme innovant de collecte participative via le portail public. Les citoyens "
    "guineens peuvent signaler directement les problemes de telecommunications qu'ils rencontrent, sans avoir besoin "
    "de creer un compte ou de s'authentifier. Ce canal de feedback crée des alertes de type SIGNALEMENT_PUBLIC qui "
    "sont integrees dans le systeme d'alertes global de la plateforme. Les signalements incluent le type de probleme, "
    "la severite estimee, la region concernee, et optionnellement l'operateur implique.",
    body_style
))

story.append(Paragraph(
    "Ce mecanisme de signalement citoyen est particulierement precieux car il permet de detecter des problemes "
    "en temps reel, souvent avant meme que les campagnes d'audit ne les identifient. Les zones blanches signalees "
    "par les usagers peuvent ainsi orienter les futures campagnes de mesure, optimisant l'allocation des ressources "
    "d'audit de l'ARPT. De plus, ce canal renforce la legitimite de l'action reglementaire en demontrant que les "
    "decisions sont prises sur la base de signalements concrets de la population.",
    body_style
))

story.append(add_heading('<b>3.1.4 Alertes Automatiques (Seuils et Depassements)</b>', h3_style, level=1))

story.append(Paragraph(
    "Le systeme genere automatiquement des alertes lorsque les metriques collectees depassent les seuils reglementaires "
    "ou les seuils de degradation definis par l'ARPT. Par exemple, une alerte de type DEGRADATION est emise lorsque "
    "la latence moyenne d'un operateur dans une region depasse un seuil critique, tandis qu'une alerte SEUIL_DEPASSE "
    "signale le franchissement d'un seuil reglementaire. Les alertes NON_CONFORMITE sont declenchees lorsqu'un operateur "
    "ne respecte pas ses obligations de couverture ou de qualite de service, et les alertes ZONE_BLANCHE identifient "
    "les zones sans couverture reseau.",
    body_style
))

story.append(Paragraph(
    "Chaque alerte est classee par niveau de severite : CRITIQUE (action immediate requise), HAUTE (action dans les "
    "24h), MOYENNE (action dans la semaine), ou BASSE (information). Les alertes sont accessibles via la cloche de "
    "notification dans l'interface, qui se rafraichit automatiquement toutes les 30 secondes. Les utilisateurs "
    "autorises peuvent marquer les alertes comme resolues une fois le probleme traite.",
    body_style
))

alert_data = [
    [Paragraph('<b>Type d\'Alerte</b>', tbl_header_style), Paragraph('<b>Code</b>', tbl_header_style), Paragraph('<b>Declencheur</b>', tbl_header_style), Paragraph('<b>Severite</b>', tbl_header_style)],
    [Paragraph('Degradation', tbl_cell_style), Paragraph('DEGRADATION', tbl_cell_center_style), Paragraph('Metriques en baisse par rapport au seuil', tbl_cell_style), Paragraph('HAUTE / CRITIQUE', tbl_cell_center_style)],
    [Paragraph('Seuil depasse', tbl_cell_style), Paragraph('SEUIL_DEPASSE', tbl_cell_center_style), Paragraph('Franchissement d\'un seuil reglementaire', tbl_cell_style), Paragraph('CRITIQUE', tbl_cell_center_style)],
    [Paragraph('Non-conformite', tbl_cell_style), Paragraph('NON_CONFORMITE', tbl_cell_center_style), Paragraph('Non-respect des obligations operateur', tbl_cell_style), Paragraph('HAUTE', tbl_cell_center_style)],
    [Paragraph('Zone blanche', tbl_cell_style), Paragraph('ZONE_BLANCHE', tbl_cell_center_style), Paragraph('Absence de couverture reseau', tbl_cell_style), Paragraph('MOYENNE / HAUTE', tbl_cell_center_style)],
    [Paragraph('Signalement public', tbl_cell_style), Paragraph('SIGNALEMENT_PUBLIC', tbl_cell_center_style), Paragraph('Signalement citoyen via portail', tbl_cell_style), Paragraph('BASSE / MOYENNE', tbl_cell_center_style)],
]

col_w5 = [AVAILABLE_WIDTH * 0.18, AVAILABLE_WIDTH * 0.22, AVAILABLE_WIDTH * 0.38, AVAILABLE_WIDTH * 0.22]
story.extend(make_table(alert_data, col_w5, 'Tableau 5 : Types d\'alertes et mecanismes de declenchement'))

story.append(add_heading('<b>3.1.5 Rapports et Documents Reglementaires</b>', h3_style, level=1))

story.append(Paragraph(
    "La derniere source de donnees est constituee par les rapports generes par la plateforme elle-meme. Cinq types "
    "de rapports sont disponibles : reglementaire (pour les obligations de reporting), operateur (analyse detaillee "
    "par operateur), public (version accessible aux citoyens), interne (pour les equipes ARPT), et benchmark "
    "(comparaison entre operateurs). Ces rapports sont generes a partir des donnees collectees et peuvent etre "
    "exportes au format CSV pour une analyse plus approfondie dans des outils externes.",
    body_style
))


# ═══════════════════════════════════════════════════════════
# SECTION 3.2: Flux de Données End-to-End
# ═══════════════════════════════════════════════════════════
story.append(add_heading('<b>3.2 Flux de Donnees End-to-End</b>', h2_style, level=1))

story.append(Paragraph(
    "Le flux de donnees dans la plateforme ONIT-PNG suit un pipeline structure en quatre etapes successives, "
    "depuis la collecte brute jusqu'a la presentation dans les tableaux de bord. Chaque etape ajoute de la valeur "
    "et de la structure aux donnees, transformant les mesures brutes en indicateurs decisionnels.",
    body_style
))

story.append(add_heading('<b>3.2.1 Etape 1 : Collecte des Donnees Brutes</b>', h3_style, level=1))

story.append(Paragraph(
    "Les donnees brutes sont collectees lors des campagnes d'audit terrain. Chaque point de mesure genere un "
    "enregistrement MesureQoS contenant l'ensemble des metriques RF, reseau, internet et QoE, associe a un "
    "operateur, une region, des coordonnees GPS, et un horodatage precis. Les campagnes sont creees dans le "
    "systeme avec un statut initial PLANIFIEE, passant a EN_COURS lors du debut des mesures, puis a TERMINEE "
    "lorsque toutes les mesures sont collectees. La plateforme gere actuellement 8 campagnes de demonstration "
    "couvrant les differentes regions et types de test.",
    body_style
))

story.append(add_heading('<b>3.2.2 Etape 2 : Agregation et Scoring</b>', h3_style, level=1))

story.append(Paragraph(
    "Les mesures brutes sont agregees par operateur et par periode pour calculer les scores composites trimestriels. "
    "Le modele ScoreOperateur stocke cinq sous-scores pour chaque operateur et chaque trimestre : le score de "
    "couverture (evaluation de l'etendue de la couverture reseau), le score de qualite de service (metriques "
    "techniques RF et reseau), le score de qualite d'experience (perception utilisateur), le score de conformite "
    "(respect des obligations reglementaires), et le score global (moyenne ponderee des quatre sous-scores).",
    body_style
))

story.append(Paragraph(
    "Le calcul des scores prend en compte des facteurs de degradation regionaux. La region de Conakry, capitale, "
    "sert de reference avec un facteur de 1.0, tandis que les regions eloignees comme Faranah (1.45) ou "
    "Nzerekore (1.35) appliquent un facteur de degradation refletant les difficultes d'infrastructure. "
    "Les operateurs sont egalement differencies : Orange Guinee beneficie des meilleures baselines de performance, "
    "suivi de MTN Guinee, puis Celcom Guinee, refletant la realite du marche telecommunications guineen.",
    body_style
))

story.append(add_heading('<b>3.2.3 Etape 3 : Filtrage par Politiques RLS</b>', h3_style, level=1))

story.append(Paragraph(
    "Avant toute presentation aux utilisateurs, les donnees sont filtrees selon les politiques de securite au niveau "
    "des lignes (Row-Level Security). Ce mecanisme garantit que chaque utilisateur n'accede qu'aux donnees autorisees "
    "par son role. Par exemple, un operateur ne peut voir que les donnees de son propre reseau, un ingenieur RF "
    "n'accede qu'aux regions qui lui sont assignees, et le public ne voit que les donnees explicitement marquees "
    "comme publiques. Ce filtrage s'effectue cote serveur dans les API endpoints, avant l'envoi des donnees au "
    "navigateur, garantissant ainsi la confidentialite meme en cas de contournement de l'interface.",
    body_style
))

story.append(add_heading('<b>3.2.4 Etape 4 : Presentation dans les Tableaux de Bord</b>', h3_style, level=1))

story.append(Paragraph(
    "Les donnees filtrees sont presentees dans les differents modules du tableau de bord. Le module DG affiche "
    "une vue strategique avec les KPIs nationaux, les classements des operateurs et la conformite SLA. Le module "
    "QoS presente les metriques detaillees avec des tendances temporelles et des comparaisons par region. Le module "
    "SIG affiche les donnees sur une carte interactive de la Guinee avec des couches de couverture et de qualite. "
    "Le module Scoring presente les scores composites avec des jauges, des radars et des recommandations. Chaque "
    "module communique avec les API backend via des appels fetch et met a jour l'interface en temps reel.",
    body_style
))


# ═══════════════════════════════════════════════════════════
# SECTION 4: Authentification et Contrôle d'Accès
# ═══════════════════════════════════════════════════════════
story.extend(add_major_section('<b>4. Authentification et Controle d\'Acces</b>', h1_style))

story.append(Paragraph(
    "La securite de la plateforme ONIT-PNG repose sur un systeme d'authentification robuste et un controle d'acces "
    "granulaire a deux niveaux : le Role-Based Access Control (RBAC) pour les actions et le Row-Level Security (RLS) "
    "pour les donnees. Cette double couche de protection garantit que chaque utilisateur n'accede qu'aux fonctionnalites "
    "et aux donnees strictement necessaires a son role, conformement aux principes de moindre privilege.",
    body_style
))

story.append(add_heading('<b>4.1 Systeme d\'Authentification</b>', h2_style, level=1))

story.append(Paragraph(
    "L'authentification est geree par NextAuth.js v4 avec un fournisseur de type Credentials (email + mot de passe). "
    "Les sessions sont basees sur des tokens JWT d'une duree maximale de 8 heures. Lors de l'authentification, le "
    "mot de passe fourni est compare au hash bcryptjs stocke dans la base de donnees. Si l'authentification reussit, "
    "un token JWT est emis contenant l'identifiant de l'utilisateur, son role, son organisation et ses permissions. "
    "Chaque connexion genere une entree dans le journal d'audit, assurant la tracabilite complete des acces.",
    body_style
))

story.append(add_heading('<b>4.2 Hierarchie des Roles (RBAC)</b>', h2_style, level=1))

story.append(Paragraph(
    "La plateforme definit neuf roles organises selon une hierarchie de priorite, du SUPER_ADMIN (priorite 100) au "
    "PUBLIC (priorite 10). Chaque role herite implicitement des permissions des roles inferieurs et dispose de "
    "permissions specifiques supplementaires. L'interface s'adapte dynamiquement au role de l'utilisateur : les "
    "onglets visibles, les actions disponibles et les donnees accessibles varient en fonction du niveau d'autorisation.",
    body_style
))

role_data = [
    [Paragraph('<b>Role</b>', tbl_header_style), Paragraph('<b>Priorite</b>', tbl_header_style), Paragraph('<b>Niveau d\'Acces</b>', tbl_header_style), Paragraph('<b>Onglets Visibles</b>', tbl_header_style)],
    [Paragraph('SUPER_ADMIN', tbl_cell_style), Paragraph('100', tbl_cell_center_style), Paragraph('Acces complet + Administration', tbl_cell_style), Paragraph('Tous + Admin', tbl_cell_style)],
    [Paragraph('DG', tbl_cell_style), Paragraph('90', tbl_cell_center_style), Paragraph('Vue strategique, toutes donnees, export', tbl_cell_style), Paragraph('Tous sauf Admin', tbl_cell_style)],
    [Paragraph('DGA', tbl_cell_style), Paragraph('80', tbl_cell_center_style), Paragraph('Meme que DG minus certaines ecritures', tbl_cell_style), Paragraph('Tous sauf Admin', tbl_cell_style)],
    [Paragraph('DIRECTEUR_TECHNIQUE', tbl_cell_style), Paragraph('70', tbl_cell_center_style), Paragraph('Gestion technique + Cybersecurite', tbl_cell_style), Paragraph('Tous sauf Admin', tbl_cell_style)],
    [Paragraph('INGENIEUR_RF', tbl_cell_style), Paragraph('60', tbl_cell_center_style), Paragraph('Mesures terrain, regions assignees', tbl_cell_style), Paragraph('Dashboard, QoS, SIG, Audit, Reports', tbl_cell_style)],
    [Paragraph('ANALYSTE_QOS', tbl_cell_style), Paragraph('50', tbl_cell_center_style), Paragraph('Lecture + export, pas d\'ecriture campagnes', tbl_cell_style), Paragraph('Dashboard, QoS, Scoring, Reports', tbl_cell_style)],
    [Paragraph('AUDITEUR', tbl_cell_style), Paragraph('40', tbl_cell_center_style), Paragraph('Lecture audit, ecriture rapports', tbl_cell_style), Paragraph('Dashboard, Audit, Reports', tbl_cell_style)],
    [Paragraph('OPERATEUR_READONLY', tbl_cell_style), Paragraph('20', tbl_cell_center_style), Paragraph('Donnees propre organisation uniquement', tbl_cell_style), Paragraph('Dashboard, QoS, Scoring', tbl_cell_style)],
    [Paragraph('PUBLIC', tbl_cell_style), Paragraph('10', tbl_cell_center_style), Paragraph('Portail public uniquement', tbl_cell_style), Paragraph('Portail public', tbl_cell_style)],
]

col_w6 = [AVAILABLE_WIDTH * 0.22, AVAILABLE_WIDTH * 0.10, AVAILABLE_WIDTH * 0.40, AVAILABLE_WIDTH * 0.28]
story.extend(make_table(role_data, col_w6, 'Tableau 6 : Hierarchie des roles et niveaux d\'acces'))

story.append(add_heading('<b>4.3 Securite au Niveau des Lignes (RLS)</b>', h2_style, level=1))

story.append(Paragraph(
    "Le Row-Level Security constitue la deuxieme couche de protection, agissant au niveau des donnees elles-memes. "
    "Dix-huit politiques d'acces aux donnees (DataAccessPolicy) definissent le perimetre de visibilite de chaque "
    "role pour chaque type de ressource. Quatre portees sont definies : 'all' (acces a toutes les donnees), "
    "'own_org' (donnees de l'organisation de l'utilisateur uniquement), 'own_region' (donnees des regions assignees), "
    "et 'public_only' (donnees publiques uniquement).",
    body_style
))

story.append(Paragraph(
    "Le filtrage RLS s'applique a travers quatre fonctions cles. La fonction getAccessibleOperators() retourne la "
    "liste des operateurs visibles selon la portee du role. La fonction getAccessibleRegions() retourne les codes "
    "des regions accessibles. La fonction getRLSScope() determine la portee applicable. Enfin, la fonction "
    "filterDataByRLS() effectue le filtrage generique cote client sur les resultats des requetes API. Par exemple, "
    "un utilisateur avec le role OPERATEUR_READONLY et l'organisation 'Orange' ne verra que les mesures, scores et "
    "alertes relatifs a Orange Guinee, sans jamais pouvoir acceder aux donnees de MTN ou Celcom.",
    body_style
))

story.append(add_heading('<b>4.4 Journal d\'Audit</b>', h2_style, level=1))

story.append(Paragraph(
    "Toutes les actions sensibles effectuees sur la plateforme sont enregistrees dans le journal d'audit. Ce journal "
    "capture le type d'action (LOGIN, READ, CREATE, UPDATE, EXPORT, DELETE), l'utilisateur qui l'a effectuee, "
    "la ressource concernee, l'adresse IP et le user agent du navigateur, ainsi que l'horodatage precis. Le journal "
    "est accessible aux roles SUPER_ADMIN et DIRECTEUR_TECHNIQUE via l'onglet Cybersecurite ou l'onglet Administration. "
    "Cette tracabilite complete est essentielle pour la conformite reglementaire et la detection d'activites suspectes.",
    body_style
))


# ═══════════════════════════════════════════════════════════
# SECTION 5: Modules Fonctionnels
# ═══════════════════════════════════════════════════════════
story.extend(add_major_section('<b>5. Modules Fonctionnels</b>', h1_style))

story.append(Paragraph(
    "La plateforme ONIT-PNG est organisee en neuf modules fonctionnels, chacun dedie a un aspect specifique de la "
    "supervision des telecommunications. Les modules sont accessibles via la barre de navigation laterale et leur "
    "visibilite depend du role de l'utilisateur connecte. Voici une description detaillee de chaque module.",
    body_style
))

modules_data = [
    [Paragraph('<b>Module</b>', tbl_header_style), Paragraph('<b>Composant</b>', tbl_header_style), Paragraph('<b>Fonctionnalites Principales</b>', tbl_header_style)],
    [Paragraph('Tableau de Bord DG', tbl_cell_style), Paragraph('DashboardDG', tbl_cell_style), Paragraph('KPIs nationaux, classements operateurs, carte couverture, conformite SLA, alertes recentes', tbl_cell_style)],
    [Paragraph('Suivi QoS', tbl_cell_style), Paragraph('DashboardQoS', tbl_cell_style), Paragraph('Metriques detaillees, tendances temporelles, benchmark operateurs, heatmap regionale', tbl_cell_style)],
    [Paragraph('SIG Cartographie', tbl_cell_style), Paragraph('DashboardSIG', tbl_cell_style), Paragraph('Carte Leaflet interactive, couches couverture/QoS/zones blanches, filtres operateurs', tbl_cell_style)],
    [Paragraph('Scoring', tbl_cell_style), Paragraph('DashboardScoring', tbl_cell_style), Paragraph('Jauges circulaires, radar comparatif, sparklines historiques, recommandations IA', tbl_cell_style)],
    [Paragraph('Audit Terrain', tbl_cell_style), Paragraph('DashboardAudit', tbl_cell_style), Paragraph('Liste campagnes, statistiques, visualisation drive test, resultats tests', tbl_cell_style)],
    [Paragraph('Rapports', tbl_cell_style), Paragraph('DashboardReports', tbl_cell_style), Paragraph('Generation par template, telechargement CSV, rapports recents, planification', tbl_cell_style)],
    [Paragraph('Portail Public', tbl_cell_style), Paragraph('DashboardPublic', tbl_cell_style), Paragraph('KPIs publics, carte couverture, comparaison operateurs, signalement citoyen, FAQ', tbl_cell_style)],
    [Paragraph('Cybersecurite', tbl_cell_style), Paragraph('DashboardCyber', tbl_cell_style), Paragraph('Score securite, vue RBAC, statut chiffrement, jauges conformite, journal audit', tbl_cell_style)],
    [Paragraph('Administration', tbl_cell_style), Paragraph('DashboardAdmin', tbl_cell_style), Paragraph('Gestion utilisateurs, recherche/filtres, creation comptes, activation/desactivation', tbl_cell_style)],
]

col_w7 = [AVAILABLE_WIDTH * 0.17, AVAILABLE_WIDTH * 0.17, AVAILABLE_WIDTH * 0.66]
story.extend(make_table(modules_data, col_w7, 'Tableau 7 : Modules fonctionnels de la plateforme'))


# ═══════════════════════════════════════════════════════════
# SECTION 6: API et Intégrations
# ═══════════════════════════════════════════════════════════
story.extend(add_major_section('<b>6. API et Integrations</b>', h1_style))

story.append(Paragraph(
    "La plateforme expose plus de dix endpoints API REST securises qui constituent l'interface entre les composants "
    "frontend et la base de donnees. Chaque endpoint applique les politiques d'authentification et de filtrage RLS "
    "appropriees, garantissant que seules les donnees autorisees sont retournees. Les endpoints supportent a la fois "
    "les lectures (GET) et les ecritures (POST, PATCH) avec des controles de permissions granulaires.",
    body_style
))

api_data = [
    [Paragraph('<b>Endpoint</b>', tbl_header_style), Paragraph('<b>Methode</b>', tbl_header_style), Paragraph('<b>Auth</b>', tbl_header_style), Paragraph('<b>Fonction</b>', tbl_header_style)],
    [Paragraph('/api/dashboard', tbl_cell_style), Paragraph('GET', tbl_cell_center_style), Paragraph('RLS', tbl_cell_center_style), Paragraph('Donnees KPIs, classements, alertes, stats regionales', tbl_cell_style)],
    [Paragraph('/api/qos', tbl_cell_style), Paragraph('GET', tbl_cell_center_style), Paragraph('Requise', tbl_cell_center_style), Paragraph('Metriques QoS agregees, tendances, benchmark, heatmap', tbl_cell_style)],
    [Paragraph('/api/map', tbl_cell_style), Paragraph('GET', tbl_cell_center_style), Paragraph('RLS', tbl_cell_center_style), Paragraph('Donnees cartographiques, points de mesure, overlays', tbl_cell_style)],
    [Paragraph('/api/scoring', tbl_cell_style), Paragraph('GET', tbl_cell_center_style), Paragraph('RLS', tbl_cell_center_style), Paragraph('Scores operateurs, sous-scores, tendances, radar', tbl_cell_style)],
    [Paragraph('/api/alerts', tbl_cell_style), Paragraph('GET/POST/PATCH', tbl_cell_center_style), Paragraph('Requise*', tbl_cell_center_style), Paragraph('Liste alertes, creation, resolution (*public pour signalement)', tbl_cell_style)],
    [Paragraph('/api/campaigns', tbl_cell_style), Paragraph('GET/POST', tbl_cell_center_style), Paragraph('Requise', tbl_cell_center_style), Paragraph('Liste campagnes, creation nouvelles campagnes', tbl_cell_style)],
    [Paragraph('/api/reports', tbl_cell_style), Paragraph('GET/POST', tbl_cell_center_style), Paragraph('RLS', tbl_cell_center_style), Paragraph('Liste rapports, generation de rapports', tbl_cell_style)],
    [Paragraph('/api/users', tbl_cell_style), Paragraph('GET/POST/PATCH', tbl_cell_center_style), Paragraph('Admin', tbl_cell_center_style), Paragraph('Gestion utilisateurs, creation, activation/desactivation', tbl_cell_style)],
    [Paragraph('/api/roles', tbl_cell_style), Paragraph('GET', tbl_cell_center_style), Paragraph('Admin', tbl_cell_center_style), Paragraph('Liste roles avec permissions', tbl_cell_style)],
    [Paragraph('/api/audit-logs', tbl_cell_style), Paragraph('GET', tbl_cell_center_style), Paragraph('Admin/Tech', tbl_cell_center_style), Paragraph('Journal d\'audit (100 dernieres entrees)', tbl_cell_style)],
]

col_w8 = [AVAILABLE_WIDTH * 0.18, AVAILABLE_WIDTH * 0.14, AVAILABLE_WIDTH * 0.10, AVAILABLE_WIDTH * 0.58]
story.extend(make_table(api_data, col_w8, 'Tableau 8 : Endpoints API de la plateforme'))


# ═══════════════════════════════════════════════════════════
# SECTION 7: Modèle de Données
# ═══════════════════════════════════════════════════════════
story.extend(add_major_section('<b>7. Modele de Donnees</b>', h1_style))

story.append(Paragraph(
    "Le modele de donnees de la plateforme ONIT-PNG est concu pour capturer l'ensemble des informations necessaires "
    "a la supervision des telecommunications. Le schema Prisma definit treize modeles couvrant les domaines RBAC, "
    "les donnees telecoms, et l'audit. La base de donnees SQLite est choque pour sa simplicite de deploiement et "
    "sa robustesse, parfaitement adaptee au volume de donnees attendu pour un observatoire national.",
    body_style
))

story.append(add_heading('<b>7.1 Modeles RBAC</b>', h2_style, level=1))

story.append(Paragraph(
    "Les modeles Role, Permission et DataAccessPolicy constituent le socle du systeme de controle d'acces. Le modele "
    "Role definit les neuf types de roles via une enumeration RoleType. Le modele Permission associe des paires "
    "resource:action aux roles, comme scoring:export ou campaign:write. Le modele DataAccessPolicy definit les "
    "politiques RLS avec la portee (all, own_org, own_region, public_only) et les filtres par region et operateur.",
    body_style
))

story.append(add_heading('<b>7.2 Modeles Telecoms</b>', h2_style, level=1))

story.append(Paragraph(
    "Les modeles Operateur et Region representent les entites geographiques et organisationnelles du systeme. "
    "Le modele Operateur stocke le nom, le code unique, le type et la licence de chaque operateur. Le modele Region "
    "contient les huit regions administratives avec leur population, leurs coordonnees GPS et leur code unique. "
    "Le modele Campagne lie les mesures aux operateurs et regions, avec un statut de progression. Le modele "
    "MesureQoS constitue le modele le plus riche, avec plus de vingt champs capturant les metriques RF, reseau, "
    "internet et QoE. Le modele ScoreOperateur agrege ces mesures en scores trimestriels composites. Enfin, les "
    "modeles Alerte et Rapport completent le systeme pour la gestion des alertes et la generation de rapports.",
    body_style
))

model_data = [
    [Paragraph('<b>Modele</b>', tbl_header_style), Paragraph('<b>Champs Cles</b>', tbl_header_style), Paragraph('<b>Role</b>', tbl_header_style)],
    [Paragraph('User', tbl_cell_style), Paragraph('email, name, password (hash), roleId, organization, isActive', tbl_cell_style), Paragraph('Comptes utilisateurs avec hachage bcryptjs', tbl_cell_style)],
    [Paragraph('Role', tbl_cell_style), Paragraph('type (enum RoleType), name, priority', tbl_cell_style), Paragraph('Definition des 9 roles hierarchiques', tbl_cell_style)],
    [Paragraph('Permission', tbl_cell_style), Paragraph('resource, action, roleId', tbl_cell_style), Paragraph('Paires resource:action liees aux roles', tbl_cell_style)],
    [Paragraph('DataAccessPolicy', tbl_cell_style), Paragraph('scope, resource, roleId, regionFilter, operatorFilter', tbl_cell_style), Paragraph('18 politiques RLS par role et ressource', tbl_cell_style)],
    [Paragraph('Operateur', tbl_cell_style), Paragraph('nom, code (unique), type, licence', tbl_cell_style), Paragraph('3 operateurs nationaux', tbl_cell_style)],
    [Paragraph('Region', tbl_cell_style), Paragraph('code (unique), nom, population, centreLat, centreLng', tbl_cell_style), Paragraph('8 regions administratives', tbl_cell_style)],
    [Paragraph('Campagne', tbl_cell_style), Paragraph('nom, type, statut, operateurId, regionId, dates', tbl_cell_style), Paragraph('Campagnes d\'audit terrain', tbl_cell_style)],
    [Paragraph('MesureQoS', tbl_cell_style), Paragraph('20+ metriques RF/reseau/internet/QoE, GPS', tbl_cell_style), Paragraph('Mesures individuelles de qualite', tbl_cell_style)],
    [Paragraph('ScoreOperateur', tbl_cell_style), Paragraph('5 sous-scores, periode, recommandation', tbl_cell_style), Paragraph('Scores trimestriels composites', tbl_cell_style)],
    [Paragraph('Alerte', tbl_cell_style), Paragraph('type, severity, message, isResolved', tbl_cell_style), Paragraph('Systeme d\'alertes multi-niveaux', tbl_cell_style)],
    [Paragraph('Rapport', tbl_cell_style), Paragraph('type, format, isPublic, contenu', tbl_cell_style), Paragraph('Generation et export de rapports', tbl_cell_style)],
    [Paragraph('AuditLog', tbl_cell_style), Paragraph('action, resource, userId, ipAddress, userAgent', tbl_cell_style), Paragraph('Journal d\'audit complet', tbl_cell_style)],
]

col_w9 = [AVAILABLE_WIDTH * 0.17, AVAILABLE_WIDTH * 0.45, AVAILABLE_WIDTH * 0.38]
story.extend(make_table(model_data, col_w9, 'Tableau 9 : Modeles de donnees du schema Prisma'))


# ═══════════════════════════════════════════════════════════
# SECTION 8: Données de Référence et Facteurs de Région
# ═══════════════════════════════════════════════════════════
story.extend(add_major_section('<b>8. Donnees de Reference et Facteurs de Region</b>', h1_style))

story.append(Paragraph(
    "La plateforme utilise un systeme de facteurs de degradation regionaux pour ajuster les metriques de performance "
    "en fonction des realites geographiques et infrastructurelles de chaque region. Ce systeme reconnait que les "
    "performances d'un operateur ne peuvent etre evaluees de maniere identique a Conakry, ou l'infrastructure "
    "est la plus developpee, et dans les regions interieures ou les defis topographiques et logistiques sont "
    "significatifs. Les facteurs sont appliques comme multiplicateurs sur les baselines de chaque operateur, "
    "simulant une degradation realiste des performances en s'eloignant de la capitale.",
    body_style
))

region_data = [
    [Paragraph('<b>Region</b>', tbl_header_style), Paragraph('<b>Code</b>', tbl_header_style), Paragraph('<b>Population</b>', tbl_header_style), Paragraph('<b>Facteur</b>', tbl_header_style), Paragraph('<b>Commentaire</b>', tbl_header_style)],
    [Paragraph('Conakry', tbl_cell_style), Paragraph('CON', tbl_cell_center_style), Paragraph('2 000 000', tbl_cell_center_style), Paragraph('1.00', tbl_cell_center_style), Paragraph('Capitale, reference nationale', tbl_cell_style)],
    [Paragraph('Kindia', tbl_cell_style), Paragraph('KIN', tbl_cell_center_style), Paragraph('1 300 000', tbl_cell_center_style), Paragraph('1.10', tbl_cell_center_style), Paragraph('Proximite Conakry, bonne infrastructure', tbl_cell_style)],
    [Paragraph('Boke', tbl_cell_style), Paragraph('BOK', tbl_cell_center_style), Paragraph('1 000 000', tbl_cell_center_style), Paragraph('1.20', tbl_cell_center_style), Paragraph('Zone miniere, infrastructure moyenne', tbl_cell_style)],
    [Paragraph('Labe', tbl_cell_style), Paragraph('LAB', tbl_cell_center_style), Paragraph('900 000', tbl_cell_center_style), Paragraph('1.25', tbl_cell_center_style), Paragraph('Relief montagneux, couverture partielle', tbl_cell_style)],
    [Paragraph('Mamou', tbl_cell_style), Paragraph('MAM', tbl_cell_center_style), Paragraph('700 000', tbl_cell_center_style), Paragraph('1.20', tbl_cell_center_style), Paragraph('Zone agricole, infrastructure limitee', tbl_cell_style)],
    [Paragraph('Faranah', tbl_cell_style), Paragraph('FAR', tbl_cell_center_style), Paragraph('500 000', tbl_cell_center_style), Paragraph('1.45', tbl_cell_center_style), Paragraph('Zone la plus isolee, degradation maximale', tbl_cell_style)],
    [Paragraph('Kankan', tbl_cell_style), Paragraph('KAN', tbl_cell_center_style), Paragraph('1 500 000', tbl_cell_center_style), Paragraph('1.15', tbl_cell_center_style), Paragraph('Deuxieme ville, infrastructure en developpement', tbl_cell_style)],
    [Paragraph('Nzerekore', tbl_cell_style), Paragraph('NZE', tbl_cell_center_style), Paragraph('1 800 000', tbl_cell_center_style), Paragraph('1.35', tbl_cell_center_style), Paragraph('Zone forestiere, defis d\'acces', tbl_cell_style)],
]

col_w10 = [AVAILABLE_WIDTH * 0.14, AVAILABLE_WIDTH * 0.10, AVAILABLE_WIDTH * 0.15, AVAILABLE_WIDTH * 0.11, AVAILABLE_WIDTH * 0.50]
story.extend(make_table(region_data, col_w10, 'Tableau 10 : Regions administratives et facteurs de degradation'))

story.append(Paragraph(
    "Les baselines operateurs refletent les differences de performance entre les trois operateurs nationaux. "
    "Orange Guinee dispose des meilleures baselines (latence de base 25ms, debit descendant 42 Mbps), suivi de "
    "MTN Guinee (latence 30ms, debit 38 Mbps), puis Celcom Guinee (latence 35ms, debit 35 Mbps). Ces baselines "
    "sont multipliees par le facteur de degradation regional pour obtenir les valeurs de reference de chaque "
    "region, auxquelles s'ajoute une variation aleatoire realiste pour simuler les fluctuations reelles du reseau.",
    body_style
))


# ═══════════════════════════════════════════════════════════
# SECTION 9: Perspectives et Évolutions
# ═══════════════════════════════════════════════════════════
story.extend(add_major_section('<b>9. Perspectives et Evolutions</b>', h1_style))

story.append(Paragraph(
    "La plateforme ONIT-PNG est concue pour evoluer et s'adapter aux besoins futurs de la regulation des "
    "telecommunications en Guinee. Plusieurs axes d'amelioration sont envisages pour les prochaines phases "
    "du projet, visant a enrichir les capacites de collecte, d'analyse et de decision de la plateforme.",
    body_style
))

story.append(add_heading('<b>9.1 Automatisation de la Collecte</b>', h2_style, level=1))

story.append(Paragraph(
    "L'integration de sondes de mesure automatisees deployees en permance sur le terrain permettrait de passer "
    "d'une collecte episodique (lors des campagnes) a une collecte continue. Ces sondes, installees sur des sites "
    "strategiques dans chaque region, transmettraient leurs mesures en temps reel via une connexion securisee, "
    "eliminant le besoin de campagnes manuelles pour les indicateurs de base. L'API de la plateforme est deja "
    "concue pour recevoir ces flux de donnees en temps reel via les endpoints POST existants.",
    body_style
))

story.append(add_heading('<b>9.2 Intelligence Artificielle et Predictibilite</b>', h2_style, level=1))

story.append(Paragraph(
    "Le module d'intelligence artificielle actuellement en place fournit des recommandations basees sur des regles. "
    "Les evolutions prevues incluent l'integration de modeles de machine learning pour la prediction des pannes "
    "reseau, la detection d'anomalies en temps reel, et l'optimisation du placement des antennes. Le SDK d'IA "
    "est deja integre dans la stack technique via le package z-ai-web-dev-sdk, permettant l'invocation de modeles "
    "de langage pour l'analyse des tendances et la generation de rapports narratifs automatiques.",
    body_style
))

story.append(add_heading('<b>9.3 Integration des Donnees Geospatiales Avancees</b>', h2_style, level=1))

story.append(Paragraph(
    "L'enrichissement du module SIG avec des donnees geospatiales supplementaires est prevu : imagerie satellite "
    "pour la couverture reseau, donnees topographiques pour la modelisation de propagation, et integration avec "
    "les systemes d'information geographique nationaux. La carte Leaflet actuelle constitue la base technique "
    "pour ces evolutions, avec la prise en charge des couches GeoJSON et des tuiles raster deja fonctionnelle.",
    body_style
))

story.append(add_heading('<b>9.4 Portail Citoyen Etendu</b>', h2_style, level=1))

story.append(Paragraph(
    "Le portail public sera enrichi avec des fonctionnalites de visualisation de donnees pour les citoyens, "
    "un systeme de cartes de couverture par localite, et des mecanismes de feedback plus elabores incluant "
    "la possibilite de joindre des photos et des fichiers aux signalements. L'objectif est de transformer "
    "les citoyens en capteurs contributifs de la qualite des telecommunications, creant un observatoire "
    "participatif a l'echelle nationale.",
    body_style
))

# ━━ Build ━━
doc.multiBuild(story)
print(f"PDF generated successfully: {output_path}")
